In [2]:
import os
import sys

print("Python location:", sys.executable)
print("Operating system:", os.name)
print("Current directory:", os.getcwd())

Python location: c:\ProgramData\anaconda3\python.exe
Operating system: nt
Current directory: c:\Users\USER\OneDrive\Desktop\BRFSS

In [3]:
import os

file_path = "decoded.csv"

print("File exists:", os.path.isfile(file_path))

if os.path.isfile(file_path):
    print("File size (MB):", round(
        os.path.getsize(file_path) / (1024**2), 2
    ))

File exists: True
File size (MB): 1203.39

In [4]:
import pandas as pd

file_path = "decoded.csv"

try:
    df_test = pd.read_csv(file_path, nrows=1000)

    print("Read successful")
    print("Rows tested:", len(df_test))
    print("Columns:", len(df_test.columns))
    print("Column names:")
    print(df_test.columns.tolist()[:10])

except Exception as e:
    print("Error:", repr(e))

Read successful
Rows tested: 1000
Columns: 301
Column names:
['State FIPS Code (_STATE)', 'File Month (FMONTH)', 'Interview Date (IDATE)', 'Interview Month (IMONTH)', 'Interview Day (IDAY)', 'Interview Year (IYEAR)', 'Final Disposition (DISPCODE)', 'Annual Sequence Number (SEQNO)', 'Primary Sampling Unit (_PSU)', 'Correct telephone number? (CTELENM1)']

In [5]:
import pandas as pd

file_path = "decoded.csv"
total_rows = 0
total_columns = None

try:
    for chunk in pd.read_csv(file_path, chunksize=100_000):
        total_rows += len(chunk)
        total_columns = len(chunk.columns)

        if total_rows % 500_000 < 100_000:
            print("Rows checked:", f"{total_rows:,}")

    print("\nFile read completed successfully")
    print("Total rows:", f"{total_rows:,}")
    print("Total columns:", total_columns)

except Exception as e:
    print("\nReading failed:", repr(e))
    print("Rows read before error:", f"{total_rows:,}")

C:\Users\USER\AppData\Local\Temp\ipykernel_25300\2597479245.py:8: DtypeWarning: Columns (9: Correct telephone number? (CTELENM1), 10: Private Residence? (PVTRESD1), 11: Do you live in college housing? (COLGHOUS), 12: Resident of State (STATERE1), 13: Cellular Telephone (CELPHON1), 14: Are you 18 years of age or older? (LADULT1), 15: Number of Adults in Household (NUMADULT), 16: Respondent selection (RESPSLC1), 17: Are you male or female? (LANDSEX3), 18: Safe time to talk (SAFETIME), 19: Correct Phone Number? (CTELNUM1), 20: Is this a cell phone? (CELLFON5), 21: Are you 18 years of age or older? (CADULT1), 22: Are you male or female? (CELLSEX3), 23: Do you live in a private residence? (PVTRESD3), 24: Do you live in college housing? (CCLGHOUS), 25: Do you currently live in  ____(state)____? (CSTATE1), 26: Do you also have a landline telephone? (LANDLINE), 27: Number of Adults in Household (HHADULT), 56: Household Landline Telephones (NUMHHOL4), 57: Residential Landline Phones (NUMPHON4), 112: When was your last blood test for high blood sugar? (PDIABTS1), 113: Ever been told by a doctor or other health professional that you have pre-diabetes or borderline diabetes? (PREDIAB2), 114: What type of diabetes do you have? (DIABTYPE), 115: Now Taking Insulin (INSULIN1), 116: Times Checked for Glycosylated Hemoglobin (CHKHEMO3), 117: Last Eye Exam Where Pupils Were Dilated (EYEEXAM1), 118: When was the last time a they took a photo of the back of your eye? (DIABEYE1), 119: When was the last time you took a course or class in how to manage your diabetes? (DIABEDU1), 120: Ever Had Feet Sores or Irritations Lasting More Than Four Weeks (FEETSORE), 122: Have you ever had the shingles or zoster vaccine? (SHINGLE2), 123: Have you ever had an H.P.V. vaccination? (HPVADVC4), 124: How many HPV shots did you receive? (HPVADSH1), 125: Received Tetanus Shot Since 2005? (TETANUS1), 126: How Many Types of Cancer? (CNCRDIFF), 127: Age Told Had Cancer (CNCRAGE), 128: Type of Cancer (CNCRTYP2), 129: Currently Receiving Treatment for Cancer (CSRVTRT3), 130: What Type of Doctor Provides Majority of Your Care (CSRVDOC1), 131: Did You Receive a Summary of Cancer Treatments Received (CSRVSUM), 132: Ever Receive Instructions From A Doctor For Follow-Up Check-Ups (CSRVRTRN), 133: Instructions Written or Printed (CSRVINST), 134: Did Health Insurance Pay For All Of Your Cancer Treatment (CSRVINSR), 135: Ever Denied Insurance Coverage Because Of Your Cancer? (CSRVDEIN), 136: Participate In Clinical Trial As Part Of Cancer Treatment? (CSRVCLIN), 137: Currently Have Physical Pain From Cancer Or Treatment? (CSRVPAIN), 138: Is Pain Under Control? (CSRVCTL2), 139: Ever Had PSA Test (PSATEST1), 140: Time Since Most Recent PSA Test (PSATIME1), 141: What was the MAIN reason you had this PSA test? (PCPSARS2), 142: Who first suggested this P.S.A. test? (PSASUGS1), 143: Did you talk about the advantages or disadvantages of P.S.A. test (PCSTALK2), 144: Have you experienced difficulties with thinking or memory that is happening more often or is getting worse? (CIMEMLO1), 145: Are you worried about these difficulties with thinking or memory? (CDWORRY), 146: Have you discussed your difficulties with thinking with a health care provider? (CDDISCU1), 147: Given up day-to-day chores due to difficulties with thinking or memory (CDHOUS1), 148: Does difficulties with thinking or memory interfere with work or social activities (CDSOCIA1), 149: Provided regular care for family or friend (CAREGIV1), 150: Relationship Of Person To Whom You Are Giving Care? (CRGVREL5), 151: What Is The Main Health Problem, Illness, Disability For Care For Person? (CRGVPRB4), 152: Does Person Being Cared For Have Alzheimer's Disease? (CRGVALZD), 153: Help with Nursing or Medical Tasks (CRGVNURS), 154: Managed personal care (CRGVPER2), 155: Managed household tasks (CRGVHOU2), 156: How Many Hours Do You Provide Care For Person? (CRGVHRS2), 157: How Long Provided Care For Person. (CRGVLNG2), 158: Live With Anyone Depressed, Mentally Ill, Or Suicidal? (ACEDEPRS), 159: Live With a Problem Drinker/Alcoholic? (ACEDRINK), 160: Live With Anyone Who Used Illegal Drugs or Abused Prescriptions? (ACEDRUGS), 161: Live With Anyone Who Served TIme in Prison or Jail? (ACEPRISN), 162: Were Your Parents Divorced/Seperated? (ACEDIVRC), 163: How Often Did Your Parents Beat Each Other Up? (ACEPUNCH), 164: How Often Did A Parent Physically Hurt You In Any Way? (ACEHURT1), 165: How Often Did A Parent Swear At You? (ACESWEAR), 166: How Often Did Anyone Ever Touch You Sexually? (ACETOUCH), 167: How Often Did Anyone Make You Touch Them Sexually? (ACETTHEM), 168: How Often Did Anyone Ever Force You to Have Sex? (ACEHVSEX), 169: Did an adult make you feel safe and protected (ACEADSAF), 170: Did an adult make sure basic needs were met (ACEADNED), 171: Satisfaction with life (LSATISFY), 172: How often get emotional support needed (EMTSUPRT), 173: How often do you feel lonely? (SDLONELY), 174: Have you lost employment or had hours reduced? (SDHEMPLY), 175: During the past 12 months have you received food stamps (FOODSTMP), 176: How often did the food that you bought not last, and you didn't have money to get more? (SDHFOOD1), 177: Were you not able to pay your bills? (SDHBILLS), 178: Were you not able to pay utility bills or threatened to lose service? (SDHUTILS), 179: Has a lack of reliable transportation kept you from appointments, meetings, work, or getting things needed (SDHTRNSP), 180: Neighborhood Safe From Crime (HOWSAFE1), 181: During the past 30 days, on how many days did you use marijuana or hashish? (MARIJAN1), 182: Did you smoke marijuana or cannabis? (MARJSMOK), 183: Did you eat marijuana or cannabis? (MARJEAT), 184: Did you vape marijuana or cannabis? (MARJVAPE), 185: Did you dab marijuana or cannabis? (MARJDAB), 186: Did you use marijuana or cannabis some other way? (MARJOTHR), 188: Interval Since Last Smoked (LASTSMK2), 189: Stopped Smoking in past 12 months (STOPSMK2), 190: Do you usually smoke menthol cigarettes? (MENTCIGS), 191: Do you usually use menthol e-cigarettes? (MENTECIG), 192: Have you heard of heated tobacco products? (HEATTBCO), 193: How often did you drink regular soda or pop that contains sugar? (SSBSUGR2), 194: How often did you drink sugar-sweetened drinks? (SSBFRUT3), 195: Any Firearms in Home (FIREARM5), 196: Any Firearms Loaded (GUNLOAD), 197: Any Loaded Firearms Also Unlocked (LOADULK2), 200: Relationship to child (RCSRLTN2), 201: Hlth pro ever said child has asthma (CASTHDX2), 202: Child still have asthma? (CASTHNO2), 203: Sexual orientation (SOMALE), 204: Sexual orientation (SOFEMALE), 205: Have you have sexual intercourse? (HADSEX), 206: Did you do anything to keep from getting pregnant? (PFPPRVN4), 207: What did you do to keep you from getting pregnant? (TYPCNTR9), 208: What was main reason for not doing anything to keep you from getting pregnant? (NOBCUSE8), 213: Metropolitan Status (_METSTAT), 214: Urban/Rural Status (_URBSTAT), 215: Metropolitan Status Code (MSCODE), 221: Child Hispanic, Latino/a, or Spanish origin calculated variable (_CHISPNC), 222: Child Non-Hispanic Race including Multiracial (_CRACE1), 223: Four level child age (CAGEG), 282: How old when you last smoked? (LCSLAST_)) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path, chunksize=100_000):
C:\Users\USER\AppData\Local\Temp\ipykernel_25300\2597479245.py:8: DtypeWarning: Columns (9: Correct telephone number? (CTELENM1), 10: Private Residence? (PVTRESD1), 11: Do you live in college housing? (COLGHOUS), 12: Resident of State (STATERE1), 13: Cellular Telephone (CELPHON1), 14: Are you 18 years of age or older? (LADULT1), 15: Number of Adults in Household (NUMADULT), 16: Respondent selection (RESPSLC1), 17: Are you male or female? (LANDSEX3), 18: Safe time to talk (SAFETIME), 19: Correct Phone Number? (CTELNUM1), 20: Is this a cell phone? (CELLFON5), 21: Are you 18 years of age or older? (CADULT1), 22: Are you male or female? (CELLSEX3), 23: Do you live in a private residence? (PVTRESD3), 24: Do you live in college housing? (CCLGHOUS), 25: Do you currently live in  ____(state)____? (CSTATE1), 26: Do you also have a landline telephone? (LANDLINE), 27: Number of Adults in Household (HHADULT), 56: Household Landline Telephones (NUMHHOL4), 57: Residential Landline Phones (NUMPHON4), 112: When was your last blood test for high blood sugar? (PDIABTS1), 113: Ever been told by a doctor or other health professional that you have pre-diabetes or borderline diabetes? (PREDIAB2), 114: What type of diabetes do you have? (DIABTYPE), 115: Now Taking Insulin (INSULIN1), 116: Times Checked for Glycosylated Hemoglobin (CHKHEMO3), 117: Last Eye Exam Where Pupils Were Dilated (EYEEXAM1), 118: When was the last time a they took a photo of the back of your eye? (DIABEYE1), 119: When was the last time you took a course or class in how to manage your diabetes? (DIABEDU1), 120: Ever Had Feet Sores or Irritations Lasting More Than Four Weeks (FEETSORE), 121: Dr. Suggest Use of Physical Activity or Exercise for Arthritis or Joint Symptoms (ARTHEXER), 123: Have you ever had an H.P.V. vaccination? (HPVADVC4), 124: How many HPV shots did you receive? (HPVADSH1), 126: How Many Types of Cancer? (CNCRDIFF), 127: Age Told Had Cancer (CNCRAGE), 128: Type of Cancer (CNCRTYP2), 129: Currently Receiving Treatment for Cancer (CSRVTRT3), 130: What Type of Doctor Provides Majority of Your Care (CSRVDOC1), 131: Did You Receive a Summary of Cancer Treatments Received (CSRVSUM), 132: Ever Receive Instructions From A Doctor For Follow-Up Check-Ups (CSRVRTRN), 133: Instructions Written or Printed (CSRVINST), 134: Did Health Insurance Pay For All Of Your Cancer Treatment (CSRVINSR), 135: Ever Denied Insurance Coverage Because Of Your Cancer? (CSRVDEIN), 136: Participate In Clinical Trial As Part Of Cancer Treatment? (CSRVCLIN), 137: Currently Have Physical Pain From Cancer Or Treatment? (CSRVPAIN), 138: Is Pain Under Control? (CSRVCTL2), 139: Ever Had PSA Test (PSATEST1), 140: Time Since Most Recent PSA Test (PSATIME1), 141: What was the MAIN reason you had this PSA test? (PCPSARS2), 142: Who first suggested this P.S.A. test? (PSASUGS1), 143: Did you talk about the advantages or disadvantages of P.S.A. test (PCSTALK2), 144: Have you experienced difficulties with thinking or memory that is happening more often or is getting worse? (CIMEMLO1), 145: Are you worried about these difficulties with thinking or memory? (CDWORRY), 146: Have you discussed your difficulties with thinking with a health care provider? (CDDISCU1), 147: Given up day-to-day chores due to difficulties with thinking or memory (CDHOUS1), 148: Does difficulties with thinking or memory interfere with work or social activities (CDSOCIA1), 149: Provided regular care for family or friend (CAREGIV1), 150: Relationship Of Person To Whom You Are Giving Care? (CRGVREL5), 151: What Is The Main Health Problem, Illness, Disability For Care For Person? (CRGVPRB4), 152: Does Person Being Cared For Have Alzheimer's Disease? (CRGVALZD), 153: Help with Nursing or Medical Tasks (CRGVNURS), 154: Managed personal care (CRGVPER2), 155: Managed household tasks (CRGVHOU2), 156: How Many Hours Do You Provide Care For Person? (CRGVHRS2), 157: How Long Provided Care For Person. (CRGVLNG2), 171: Satisfaction with life (LSATISFY), 172: How often get emotional support needed (EMTSUPRT), 173: How often do you feel lonely? (SDLONELY), 174: Have you lost employment or had hours reduced? (SDHEMPLY), 175: During the past 12 months have you received food stamps (FOODSTMP), 176: How often did the food that you bought not last, and you didn't have money to get more? (SDHFOOD1), 177: Were you not able to pay your bills? (SDHBILLS), 178: Were you not able to pay utility bills or threatened to lose service? (SDHUTILS), 179: Has a lack of reliable transportation kept you from appointments, meetings, work, or getting things needed (SDHTRNSP), 180: Neighborhood Safe From Crime (HOWSAFE1), 181: During the past 30 days, on how many days did you use marijuana or hashish? (MARIJAN1), 182: Did you smoke marijuana or cannabis? (MARJSMOK), 183: Did you eat marijuana or cannabis? (MARJEAT), 184: Did you vape marijuana or cannabis? (MARJVAPE), 185: Did you dab marijuana or cannabis? (MARJDAB), 186: Did you use marijuana or cannabis some other way? (MARJOTHR), 188: Interval Since Last Smoked (LASTSMK2), 189: Stopped Smoking in past 12 months (STOPSMK2), 190: Do you usually smoke menthol cigarettes? (MENTCIGS), 191: Do you usually use menthol e-cigarettes? (MENTECIG), 192: Have you heard of heated tobacco products? (HEATTBCO), 193: How often did you drink regular soda or pop that contains sugar? (SSBSUGR2), 194: How often did you drink sugar-sweetened drinks? (SSBFRUT3), 195: Any Firearms in Home (FIREARM5), 196: Any Firearms Loaded (GUNLOAD), 197: Any Loaded Firearms Also Unlocked (LOADULK2), 200: Relationship to child (RCSRLTN2), 201: Hlth pro ever said child has asthma (CASTHDX2), 202: Child still have asthma? (CASTHNO2), 203: Sexual orientation (SOMALE), 204: Sexual orientation (SOFEMALE), 205: Have you have sexual intercourse? (HADSEX), 206: Did you do anything to keep from getting pregnant? (PFPPRVN4), 207: What did you do to keep you from getting pregnant? (TYPCNTR9), 208: What was main reason for not doing anything to keep you from getting pregnant? (NOBCUSE8), 215: Metropolitan Status Code (MSCODE), 221: Child Hispanic, Latino/a, or Spanish origin calculated variable (_CHISPNC), 222: Child Non-Hispanic Race including Multiracial (_CRACE1), 223: Four level child age (CAGEG), 282: How old when you last smoked? (LCSLAST_)) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(file_path, chunksize=100_000):

File read completed successfully
Total rows: 457,670
Total columns: 301

In [6]:
import pandas as pd

file_path = "decoded.csv"

df_preview = pd.read_csv(file_path, nrows=5, low_memory=False)

for col in df_preview.columns:
    print(col)

State FIPS Code (_STATE)
File Month (FMONTH)
Interview Date (IDATE)
Interview Month (IMONTH)
Interview Day (IDAY)
Interview Year (IYEAR)
Final Disposition (DISPCODE)
Annual Sequence Number (SEQNO)
Primary Sampling Unit (_PSU)
Correct telephone number? (CTELENM1)
Private Residence? (PVTRESD1)
Do you live in college housing? (COLGHOUS)
Resident of State (STATERE1)
Cellular Telephone (CELPHON1)
Are you 18 years of age or older? (LADULT1)
Number of Adults in Household (NUMADULT)
Respondent selection (RESPSLC1)
Are you male or female? (LANDSEX3)
Safe time to talk (SAFETIME)
Correct Phone Number? (CTELNUM1)
Is this a cell phone? (CELLFON5)
Are you 18 years of age or older? (CADULT1)
Are you male or female? (CELLSEX3)
Do you live in a private residence? (PVTRESD3)
Do you live in college housing? (CCLGHOUS)
Do you currently live in  ____(state)____? (CSTATE1)
Do you also have a landline telephone? (LANDLINE)
Number of Adults in Household (HHADULT)
Sex of Respondent (SEXVAR)
General Health (GENHLTH)
Number of Days Physical Health Not Good (PHYSHLTH)
Number of Days Mental Health Not Good (MENTHLTH)
Poor Physical or Mental Health (POORHLTH)
What is Your Current Primary Source of Health Care Coverage? (PRIMINS2)
Have Personal Health Care Provider? (PERSDOC3)
Could Not Afford To See Doctor (MEDCOST1)
Length of time since last routine checkup (CHECKUP1)
Exercise in Past 30 Days (EXERANY2)
Last Visited Dentist or Dental Clinic (LASTDEN4)
Number of Permanent Teeth Removed (RMVTETH4)
Ever Diagnosed with Heart Attack (CVDINFR4)
Ever Diagnosed with Angina or Coronary Heart Disease (CVDCRHD4)
Ever Diagnosed with a Stroke (CVDSTRK3)
Ever Told Had Asthma (ASTHMA3)
Still Have Asthma (ASTHNOW)
(Ever told) (you had) skin cancer that is not melanoma? (CHCSCNC1)
(Ever told) (you had)  melanoma or any other types of cancer? (CHCOCNC1)
Ever told you had C.O.P.D. emphysema or chronic bronchitis? (CHCCOPD3)
(Ever told) you had a depressive disorder (ADDEPEV3)
Ever told you have kidney disease? (CHCKDNY2)
Told Had Arthritis (HAVARTH4)
(Ever told) you had diabetes (DIABETE4)
Age When First Told You Had Diabetes (DIABAGE4)
Marital Status (MARITAL)
Education Level (EDUCA)
Own or Rent Home (RENTHOM1)
Household Landline Telephones (NUMHHOL4)
Residential Landline Phones (NUMPHON4)
Do you have a cell phone for your personal use? (CPDEMO1C)
Are You A Veteran (VETERAN3)
Employment Status (EMPLOY1)
Number of Children in Household (CHILDREN)
Income Level (INCOME3)
Pregnancy Status (PREGNANT)
Reported Weight in Pounds (WEIGHT2)
Reported Height in Feet and Inches (HEIGHT3)
Are you deaf or do you have serious difficulty hearing? (DEAF)
Blind or Difficulty seeing (BLIND)
Difficulty Concentrating or Remembering (DECIDE)
Difficulty Walking or Climbing Stairs (DIFFWALK)
Difficulty Dressing or Bathing (DIFFDRES)
Difficulty Doing Errands Alone (DIFFALON)
Have You Ever Had a Mammogram (HADMAM)
How Long since Last Mammogram (HOWLONG)
Have you ever had a cervical cancer screening test? (CERVSCRN)
Time since last cervical cancer screening test (CRVCLCNC)
Have a PAP test and recent cervical cancer screening (CRVCLPAP)
Have an H.P.V. test and recent cervical cancer screening (CRVCLHPV)
Had Hysterectomy (HADHYST2)
Ever Had Sigmoidoscopy/Colonoscopy (HADSIGM4)
Ever had a colonoscopy, sigmoidoscopy, or both (COLNSIGM)
How long since you had colonoscopy (COLNTES1)
How long since you had sigmoidoscopy (SIGMTES1)
Time Since Last Sigmoidoscopy/Colonoscopy (LASTSIG4)
Ever had any other kind of test for colorectal cancer (COLNCNCR)
Ever had a virtual colonoscopy (VIRCOLO1)
How long since you had  virtual colonoscopy (VCLNTES2)
Ever had stool test? (SMALSTOL)
How long since you had stool test? (STOLTEST)
Ever had stool DNA test? (STOOLDN2)
Was test part of Cologuard test? (BLDSTFIT)
How long since you had stool DNA (SDNATES1)
Smoked at Least 100 Cigarettes (SMOKE100)
Frequency of Days Now Smoking (SMOKDAY2)
Use of Smokeless Tobacco Products (USENOW3)
Do you now use e-cigarettes, or vaping products every day, some days, or not at all? (ECIGNOW3)
How old when you first started smoking? (LCSFIRST)
On average, how many cigarettes do you smoke each day? (LCSNUMCG)
Did you have a CT or CAT scan? (LCSCTSC1)
Were any CT or CAT scans done to check for lung cancer? (LCSSCNCR)
When did you have your most recent CT or CAT scan? (LCSCTWHN)
Days in past 30 had alcoholic beverage (ALCDAY4)
Avg alcoholic drinks per day in past 30 (AVEDRNK4)
Binge Drinking (DRNK3GE5)
Most drinks on single occasion past 30 days (MAXDRNKS)
Adult flu shot/spray past 12 mos (FLUSHOT7)
When did you receive your most recent seasonal flu shot/spray? (FLSHTMY3)
Where did you get your last flu shot/vaccine? (IMFVPLA5)
Pneumonia shot ever (PNEUVAC4)
Ever tested H.I.V. (HIVTST7)
Month and Year of Last HIV Test (HIVTSTD3)
Do Any High Risk Situations Apply (HIVRISK5)
When was your last blood test for high blood sugar? (PDIABTS1)
Ever been told by a doctor or other health professional that you have pre-diabetes or borderline diabetes? (PREDIAB2)
What type of diabetes do you have? (DIABTYPE)
Now Taking Insulin (INSULIN1)
Times Checked for Glycosylated Hemoglobin (CHKHEMO3)
Last Eye Exam Where Pupils Were Dilated (EYEEXAM1)
When was the last time a they took a photo of the back of your eye? (DIABEYE1)
When was the last time you took a course or class in how to manage your diabetes? (DIABEDU1)
Ever Had Feet Sores or Irritations Lasting More Than Four Weeks (FEETSORE)
Dr. Suggest Use of Physical Activity or Exercise for Arthritis or Joint Symptoms (ARTHEXER)
Have you ever had the shingles or zoster vaccine? (SHINGLE2)
Have you ever had an H.P.V. vaccination? (HPVADVC4)
How many HPV shots did you receive? (HPVADSH1)
Received Tetanus Shot Since 2005? (TETANUS1)
How Many Types of Cancer? (CNCRDIFF)
Age Told Had Cancer (CNCRAGE)
Type of Cancer (CNCRTYP2)
Currently Receiving Treatment for Cancer (CSRVTRT3)
What Type of Doctor Provides Majority of Your Care (CSRVDOC1)
Did You Receive a Summary of Cancer Treatments Received (CSRVSUM)
Ever Receive Instructions From A Doctor For Follow-Up Check-Ups (CSRVRTRN)
Instructions Written or Printed (CSRVINST)
Did Health Insurance Pay For All Of Your Cancer Treatment (CSRVINSR)
Ever Denied Insurance Coverage Because Of Your Cancer? (CSRVDEIN)
Participate In Clinical Trial As Part Of Cancer Treatment? (CSRVCLIN)
Currently Have Physical Pain From Cancer Or Treatment? (CSRVPAIN)
Is Pain Under Control? (CSRVCTL2)
Ever Had PSA Test (PSATEST1)
Time Since Most Recent PSA Test (PSATIME1)
What was the MAIN reason you had this PSA test? (PCPSARS2)
Who first suggested this P.S.A. test? (PSASUGS1)
Did you talk about the advantages or disadvantages of P.S.A. test (PCSTALK2)
Have you experienced difficulties with thinking or memory that is happening more often or is getting worse? (CIMEMLO1)
Are you worried about these difficulties with thinking or memory? (CDWORRY)
Have you discussed your difficulties with thinking with a health care provider? (CDDISCU1)
Given up day-to-day chores due to difficulties with thinking or memory (CDHOUS1)
Does difficulties with thinking or memory interfere with work or social activities (CDSOCIA1)
Provided regular care for family or friend (CAREGIV1)
Relationship Of Person To Whom You Are Giving Care? (CRGVREL5)
What Is The Main Health Problem, Illness, Disability For Care For Person? (CRGVPRB4)
Does Person Being Cared For Have Alzheimer's Disease? (CRGVALZD)
Help with Nursing or Medical Tasks (CRGVNURS)
Managed personal care (CRGVPER2)
Managed household tasks (CRGVHOU2)
How Many Hours Do You Provide Care For Person? (CRGVHRS2)
How Long Provided Care For Person. (CRGVLNG2)
Live With Anyone Depressed, Mentally Ill, Or Suicidal? (ACEDEPRS)
Live With a Problem Drinker/Alcoholic? (ACEDRINK)
Live With Anyone Who Used Illegal Drugs or Abused Prescriptions? (ACEDRUGS)
Live With Anyone Who Served TIme in Prison or Jail? (ACEPRISN)
Were Your Parents Divorced/Seperated? (ACEDIVRC)
How Often Did Your Parents Beat Each Other Up? (ACEPUNCH)
How Often Did A Parent Physically Hurt You In Any Way? (ACEHURT1)
How Often Did A Parent Swear At You? (ACESWEAR)
How Often Did Anyone Ever Touch You Sexually? (ACETOUCH)
How Often Did Anyone Make You Touch Them Sexually? (ACETTHEM)
How Often Did Anyone Ever Force You to Have Sex? (ACEHVSEX)
Did an adult make you feel safe and protected (ACEADSAF)
Did an adult make sure basic needs were met (ACEADNED)
Satisfaction with life (LSATISFY)
How often get emotional support needed (EMTSUPRT)
How often do you feel lonely? (SDLONELY)
Have you lost employment or had hours reduced? (SDHEMPLY)
During the past 12 months have you received food stamps (FOODSTMP)
How often did the food that you bought not last, and you didn't have money to get more? (SDHFOOD1)
Were you not able to pay your bills? (SDHBILLS)
Were you not able to pay utility bills or threatened to lose service? (SDHUTILS)
Has a lack of reliable transportation kept you from appointments, meetings, work, or getting things needed (SDHTRNSP)
Neighborhood Safe From Crime (HOWSAFE1)
During the past 30 days, on how many days did you use marijuana or hashish? (MARIJAN1)
Did you smoke marijuana or cannabis? (MARJSMOK)
Did you eat marijuana or cannabis? (MARJEAT)
Did you vape marijuana or cannabis? (MARJVAPE)
Did you dab marijuana or cannabis? (MARJDAB)
Did you use marijuana or cannabis some other way? (MARJOTHR)
USEMRJN4
Interval Since Last Smoked (LASTSMK2)
Stopped Smoking in past 12 months (STOPSMK2)
Do you usually smoke menthol cigarettes? (MENTCIGS)
Do you usually use menthol e-cigarettes? (MENTECIG)
Have you heard of heated tobacco products? (HEATTBCO)
How often did you drink regular soda or pop that contains sugar? (SSBSUGR2)
How often did you drink sugar-sweetened drinks? (SSBFRUT3)
Any Firearms in Home (FIREARM5)
Any Firearms Loaded (GUNLOAD)
Any Loaded Firearms Also Unlocked (LOADULK2)
RCSGEND1
RCSXBRTH
Relationship to child (RCSRLTN2)
Hlth pro ever said child has asthma (CASTHDX2)
Child still have asthma? (CASTHNO2)
Sexual orientation (SOMALE)
Sexual orientation (SOFEMALE)
Have you have sexual intercourse? (HADSEX)
Did you do anything to keep from getting pregnant? (PFPPRVN4)
What did you do to keep you from getting pregnant? (TYPCNTR9)
What was main reason for not doing anything to keep you from getting pregnant? (NOBCUSE8)
Questionnaire Version Identifier (QSTVER)
Language identifier (QSTLANG)
HPVDSHT
ICFQSTVR
Metropolitan Status (_METSTAT)
Urban/Rural Status (_URBSTAT)
Metropolitan Status Code (MSCODE)
Sample Design Stratification Variable (_STSTR)
Stratum weight (_STRWT)
Raw weighting factor used in raking (_RAWRAKE)
Design weight use in raking (_WT2RAKE)
Imputed race/ethnicity value (_IMPRACE)
Child Hispanic, Latino/a, or Spanish origin calculated variable (_CHISPNC)
Child Non-Hispanic Race including Multiracial (_CRACE1)
Four level child age (CAGEG)
Final child weight: Land-line and Cell-Phone data (_CLLCPWT)
Dual Phone Use Categories (_DUALUSE)
Dual Phone Use Correction Factor (_DUALCOR)
Truncated design weight used in adult combined land line and cell phone raking (_LLCPWT2)
Final weight: Land-line and cell-phone data (_LLCPWT)
Adults with good or better health (_RFHLTH)
Computed Physical Health Status (_PHYS14D)
Computed Mental Health Status (_MENT14D)
Have any health insurance (_HLTHPL2)
Respondents aged 18-64 with health insurance (_HCVU654)
Leisure Time Physical Activity Calculated Variable (_TOTINDA)
Adults aged 18+ that have had permanent teeth extracted (_EXTETH3)
Adults aged 65+ who have had all their natural teeth extracted (_ALTETH3)
Adults that have visited a dentist, dental hygenist or dental clinic within the past year (_DENVST3)
Ever had CHD or MI (_MICHD)
Lifetime Asthma Calculated Variable (_LTASTH1)
Current Asthma Calculated Variable (_CASTHM1)
Computed Asthma Status (_ASTHMS1)
Respondents diagnosed with arthritis (_DRDXAR2)
Calculated non-Hispanic Race including multiracial (_MRACE1)
Hispanic, Latino/a, or Spanish origin calculated variable (_HISPANC)
Computed Race-Ethnicity grouping (_RACE)
Create Computed Non-Hispanic Whites/All Others Race Categories Race/Ethnic Group Codes Used In Post-Stratification Variable (_RACEG21)
Computed Five level race/ethnicity category. (_RACEGR3)
Computed race groups used for internet prevalence tables (_RACEPRV)
Calculated sex variable (_SEX)
Reported age in five-year age categories calculated variable (_AGEG5YR)
Reported age in two age groups calculated variable (_AGE65YR)
Imputed Age value collapsed above 80 (_AGE80)
Imputed age in six groups (_AGE_G)
Computed Height in Inches (HTIN4)
Computed Height in Meters (HTM4)
Computed Weight in Kilograms (WTKG3)
Computed body mass index (_BMI5)
Computed body mass index categories (_BMI5CAT)
Overweight or obese calculated variable (_RFBMI5)
Computed number of children in household (_CHLDCNT)
Computed level of education completed categories (_EDUCAG)
Computed income categories (_INCOMG1)
Women respondents aged 40+ who have had a mammogram in the past two years (_RFMAM23)
Women respondents aged 40-74 that have had a mammogram in the past two years (_MAM402Y)
Female respondents that have had a cervical screening test (_CRVSCRN)
Female respondents with and intact cervix, aged 21-65, who have had a pap test in the past three years (_RFPAP37)
Female respondents with and intact cervix, aged 30-65, who have had an HPV test in the past five years (_HPV5YR1)
Female respondents with an intact cervix, aged 21-65 that have had a pap test in last 3 years or aged 30-65 that have had an HPV test in last 5 years (_PAPHPV1)
Had colonoscopy calculated variable (_HADCOLN)
Respondents aged 45-75 who have had a colonoscopy within the past ten years (_CLNSCP2)
Had sigmoidoscopy calculated variable (_HADSIGM)
Respondents aged 45-75 who have had a sigmoidoscopy within the past five years (_SGMSCP2)
Respondents aged 45-75 who have had a sigmoidoscopy within the past ten years (_SGMS102)
Respondents aged 45-75 who have had a stool test within the past year (_RFBLDS6)
Respondents aged 45-75 who have had a stool DNA test within the past three years (_STOLDN2)
Respondents aged 45-75 who have had a virtual colonoscopy within the past five years (_VIRCOL2)
Respondents aged 45-75 who have had a sigmoidoscopy within the past ten years and a blood stool test in the past year (_SBONTI2)
Respondents aged 45-75 who have fully met the USPSTF recommendations (_CRCREC3)
Computed Smoking Status (_SMOKER3)
Current Smoking Calculated Variable (_RFSMOK3)
Current E-cigarette User Calculated Variable (_CURECI3)
How old when you last smoked? (LCSLAST_)
On average, how many cigarettes do you smoke each day? (LCSNUMC_)
Lung Cancer Screening Age Groups (_LCSAGE)
Number of years smoked cigarettes (_LCSYSMK)
Number of packs of cigarettes smoked per day (_PACKDAY)
Years smoked reported packs per day (_PACKYRS)
Number of years since quit smoking cigarettes (_LCSYQTS)
LCS Smoking Group (_LCSSMKG)
USPSTF eligibility for Screening (_LCSELIG)
Had Chest CT Scan for Lung Cancer (_LCSCTSN)
Meet USPSTF Lung Cancer Screening Guidelines (_LCSPSTF)
Drink any alcoholic beverages in past 30 days (DRNKANY6)
Computed drink-occasions-per-day (DROCDY4_)
Binge Drinking Calculated Variable (_RFBING6)
Computed number of drinks of alcohol beverages per week (_DRNKWK3)
Heavy Alcohol Consumption  Calculated Variable (_RFDRHV9)
Flu Shot Calculated Variable (_FLSHOT7)
Pneumonia Vaccination Calculated Variable (_PNEUMO3)
Ever been tested for HIV calculated variable (_AIDTST4)

In [7]:

import pandas as pd

file_path = "decoded.csv"

table1_variables = [
    "CVDINFR4", "CVDCRHD4", "CVDSTRK3",
    "ASTHMA3", "ASTHNOW", "CHCSCNC1", "CHCOCNC1",
    "CHCCOPD3", "ADDEPEV3", "CHCKDNY2", "HAVARTH4",
    "DIABETE4", "DIABAGE4", "PREDIAB2", "DIABTYPE",
    "_MICHD", "_LTASTH1", "_CASTHM1", "_ASTHMS1",
    "_DRDXAR2", "CNCRDIFF", "CNCRAGE", "CNCRTYP2",
    "CSRVTRT3"
]

# Read source column names
original_columns = pd.read_csv(file_path, nrows=0).columns.tolist()

# Match variable codes to actual source column names
selected_columns = [
    col for col in original_columns
    if any(
        col == var or col.endswith(f"({var})")
        for var in table1_variables
    )
]

# Preview first 5 rows
table1_preview = pd.read_csv(
    file_path,
    usecols=selected_columns,
    nrows=5,
    dtype=str,
    encoding="utf-8-sig"
)

print("Table 1: Chronic Diseases and Comorbidities")
print("Rows:", len(table1_preview))
print("Columns found:", len(selected_columns))
print("Selected columns:", selected_columns)

display(table1_preview)

Table 1: Chronic Diseases and Comorbidities
Rows: 5
Columns found: 24
Selected columns: ['Ever Diagnosed with Heart Attack (CVDINFR4)', 'Ever Diagnosed with Angina or Coronary Heart Disease (CVDCRHD4)', 'Ever Diagnosed with a Stroke (CVDSTRK3)', 'Ever Told Had Asthma (ASTHMA3)', 'Still Have Asthma (ASTHNOW)', '(Ever told) (you had) skin cancer that is not melanoma? (CHCSCNC1)', '(Ever told) (you had)  melanoma or any other types of cancer? (CHCOCNC1)', 'Ever told you had C.O.P.D. emphysema or chronic bronchitis? (CHCCOPD3)', '(Ever told) you had a depressive disorder (ADDEPEV3)', 'Ever told you have kidney disease? (CHCKDNY2)', 'Told Had Arthritis (HAVARTH4)', '(Ever told) you had diabetes (DIABETE4)', 'Age When First Told You Had Diabetes (DIABAGE4)', 'Ever been told by a doctor or other health professional that you have pre-diabetes or borderline diabetes? (PREDIAB2)', 'What type of diabetes do you have? (DIABTYPE)', 'How Many Types of Cancer? (CNCRDIFF)', 'Age Told Had Cancer (CNCRAGE)', 'Type of Cancer (CNCRTYP2)', 'Currently Receiving Treatment for Cancer (CSRVTRT3)', 'Ever had CHD or MI (_MICHD)', 'Lifetime Asthma Calculated Variable (_LTASTH1)', 'Current Asthma Calculated Variable (_CASTHM1)', 'Computed Asthma Status (_ASTHMS1)', 'Respondents diagnosed with arthritis (_DRDXAR2)']

,Ever Diagnosed with Heart Attack (CVDINFR4),Ever Diagnosed with Angina or Coronary Heart Disease (CVDCRHD4),Ever Diagnosed with a Stroke (CVDSTRK3),Ever Told Had Asthma (ASTHMA3),Still Have Asthma (ASTHNOW),(Ever told) (you had) skin cancer that is not melanoma? (CHCSCNC1),(Ever told) (you had) melanoma or any other types of cancer? (CHCOCNC1),Ever told you had C.O.P.D. emphysema or chronic bronchitis? (CHCCOPD3),(Ever told) you had a depressive disorder (ADDEPEV3),Ever told you have kidney disease? (CHCKDNY2),...,What type of diabetes do you have? (DIABTYPE),How Many Types of Cancer? (CNCRDIFF),Age Told Had Cancer (CNCRAGE),Type of Cancer (CNCRTYP2),Currently Receiving Treatment for Cancer (CSRVTRT3),Ever had CHD or MI (_MICHD),Lifetime Asthma Calculated Variable (_LTASTH1),Current Asthma Calculated Variable (_CASTHM1),Computed Asthma Status (_ASTHMS1),Respondents diagnosed with arthritis (_DRDXAR2)
0,No,No,No,No - Go to Section 06.06 CHCSCNC1,NaN,Yes,No,No,No,No,...,NaN,NaN,NaN,NaN,NaN,Did not report having MI or CHD,No,No,Never,Diagnosed with arthritis
1,No,Yes,No,No - Go to Section 06.06 CHCSCNC1,NaN,No,No,No,No,No,...,NaN,NaN,NaN,NaN,NaN,Reported having MI or CHD,No,No,Never,Diagnosed with arthritis
2,No,No,No,No - Go to Section 06.06 CHCSCNC1,NaN,No,No,No,No,No,...,NaN,NaN,NaN,NaN,NaN,Did not report having MI or CHD,No,No,Never,Diagnosed with arthritis
3,No,No,No,No - Go to Section 06.06 CHCSCNC1,NaN,Yes,No,No,No,No,...,NaN,NaN,NaN,NaN,NaN,Did not report having MI or CHD,No,No,Never,Diagnosed with arthritis
4,No,No,No,No - Go to Section 06.06 CHCSCNC1,NaN,No,No,No,No,No,...,NaN,NaN,NaN,NaN,NaN,Did not report having MI or CHD,No,No,Never,Not diagnosed with arthritis

In [8]:

import pandas as pd

file_path = "decoded.csv"

# Table 2: Demographic / Age
table2_variables = [
    "SEXVAR", "_SEX", "_AGEG5YR", "_AGE65YR", "_AGE80",
    "_AGE_G", "_IMPRACE", "_MRACE1", "_HISPANC", "_RACE",
    "_RACEG21", "_RACEGR3", "_RACEPRV", "_METSTAT",
    "_URBSTAT", "MSCODE", "_STATE", "FMONTH", "IDATE",
    "IMONTH", "IDAY", "IYEAR", "DISPCODE", "SEQNO",
    "_PSU", "_STSTR", "_STRWT", "_RAWRAKE", "_WT2RAKE",
    "_DUALUSE", "_DUALCOR", "_LLCPWT2", "_LLCPWT",
    "QSTVER", "QSTLANG"
]

# Read source column names
original_columns = pd.read_csv(file_path, nrows=0).columns.tolist()

# Match variable codes to actual column names
selected_columns = [
    col for col in original_columns
    if any(
        col == var or col.endswith(f"({var})")
        for var in table2_variables
    )
]

# Preview the first 5 rows
table2_preview = pd.read_csv(
    file_path,
    usecols=selected_columns,
    nrows=5,
    dtype=str,
    encoding="utf-8-sig"
)

print("Table 2: Demographic / Age")
print("Rows:", len(table2_preview))
print("Columns found:", len(selected_columns))
print("Selected columns:", selected_columns)

display(table2_preview)

Table 2: Demographic / Age
Rows: 5
Columns found: 35
Selected columns: ['State FIPS Code (_STATE)', 'File Month (FMONTH)', 'Interview Date (IDATE)', 'Interview Month (IMONTH)', 'Interview Day (IDAY)', 'Interview Year (IYEAR)', 'Final Disposition (DISPCODE)', 'Annual Sequence Number (SEQNO)', 'Primary Sampling Unit (_PSU)', 'Sex of Respondent (SEXVAR)', 'Questionnaire Version Identifier (QSTVER)', 'Language identifier (QSTLANG)', 'Metropolitan Status (_METSTAT)', 'Urban/Rural Status (_URBSTAT)', 'Metropolitan Status Code (MSCODE)', 'Sample Design Stratification Variable (_STSTR)', 'Stratum weight (_STRWT)', 'Raw weighting factor used in raking (_RAWRAKE)', 'Design weight use in raking (_WT2RAKE)', 'Imputed race/ethnicity value (_IMPRACE)', 'Dual Phone Use Categories (_DUALUSE)', 'Dual Phone Use Correction Factor (_DUALCOR)', 'Truncated design weight used in adult combined land line and cell phone raking (_LLCPWT2)', 'Final weight: Land-line and cell-phone data (_LLCPWT)', 'Calculated non-Hispanic Race including multiracial (_MRACE1)', 'Hispanic, Latino/a, or Spanish origin calculated variable (_HISPANC)', 'Computed Race-Ethnicity grouping (_RACE)', 'Create Computed Non-Hispanic Whites/All Others Race Categories Race/Ethnic Group Codes Used In Post-Stratification Variable (_RACEG21)', 'Computed Five level race/ethnicity category. (_RACEGR3)', 'Computed race groups used for internet prevalence tables (_RACEPRV)', 'Calculated sex variable (_SEX)', 'Reported age in five-year age categories calculated variable (_AGEG5YR)', 'Reported age in two age groups calculated variable (_AGE65YR)', 'Imputed Age value collapsed above 80 (_AGE80)', 'Imputed age in six groups (_AGE_G)']

,State FIPS Code (_STATE),File Month (FMONTH),Interview Date (IDATE),Interview Month (IMONTH),Interview Day (IDAY),Interview Year (IYEAR),Final Disposition (DISPCODE),Annual Sequence Number (SEQNO),Primary Sampling Unit (_PSU),Sex of Respondent (SEXVAR),...,"Hispanic, Latino/a, or Spanish origin calculated variable (_HISPANC)",Computed Race-Ethnicity grouping (_RACE),Create Computed Non-Hispanic Whites/All Others Race Categories Race/Ethnic Group Codes Used In Post-Stratification Variable (_RACEG21),Computed Five level race/ethnicity category. (_RACEGR3),Computed race groups used for internet prevalence tables (_RACEPRV),Calculated sex variable (_SEX),Reported age in five-year age categories calculated variable (_AGEG5YR),Reported age in two age groups calculated variable (_AGE65YR),Imputed Age value collapsed above 80 (_AGE80),Imputed age in six groups (_AGE_G)
0,Alabama,February,2024-02-28,February,28,2024,Completed Interview,2024000001,2024000001,Female,...,"Not of Hispanic, Latino/a, or Spanish origin","White only, non-Hispanic",Non-Hispanic White,"White only, Non-Hispanic","White only, non-Hispanic",Female,Age 75 to 79,Age 65 or older,78,Age 65 or older
1,Alabama,February,2024-02-21,February,21,2024,Completed Interview,2024000002,2024000002,Male,...,"Not of Hispanic, Latino/a, or Spanish origin","White only, non-Hispanic",Non-Hispanic White,"White only, Non-Hispanic","White only, non-Hispanic",Male,Age 80 or older,Age 65 or older,80,Age 65 or older
2,Alabama,February,2024-02-21,February,21,2024,Completed Interview,2024000003,2024000003,Male,...,"Not of Hispanic, Latino/a, or Spanish origin","White only, non-Hispanic",Non-Hispanic White,"White only, Non-Hispanic","White only, non-Hispanic",Male,Age 55 to 59,Age 18 to 64,59,Age 55 to 64
3,Alabama,February,2024-02-28,February,28,2024,Completed Interview,2024000004,2024000004,Male,...,"Not of Hispanic, Latino/a, or Spanish origin","White only, non-Hispanic",Non-Hispanic White,"White only, Non-Hispanic","White only, non-Hispanic",Male,Age 80 or older,Age 65 or older,80,Age 65 or older
4,Alabama,February,2024-02-21,February,21,2024,Completed Interview,2024000005,2024000005,Male,...,"Not of Hispanic, Latino/a, or Spanish origin","White only, non-Hispanic",Non-Hispanic White,"White only, Non-Hispanic","White only, non-Hispanic",Male,Age 45 to 49,Age 18 to 64,47,Age 45 to 54

In [9]:

import pandas as pd

file_path = "decoded.csv"

# Table 3: Obesity and Anthropometric Risk Factors
table3_variables = [
    "WEIGHT2",
    "HEIGHT3",
    "HTIN4",
    "HTM4",
    "WTKG3",
    "_BMI5",
    "_BMI5CAT",
    "_RFBMI5"
]

# Read source column names
original_columns = pd.read_csv(file_path, nrows=0).columns.tolist()

# Match variable codes to actual column names
selected_columns = [
    col for col in original_columns
    if any(
        col == var or col.endswith(f"({var})")
        for var in table3_variables
    )
]

# Preview first 5 rows
table3_preview = pd.read_csv(
    file_path,
    usecols=selected_columns,
    nrows=5,
    dtype=str,
    encoding="utf-8-sig"
)

print("Table 3: Obesity and Anthropometric Risk Factors")
print("Rows:", len(table3_preview))
print("Columns found:", len(selected_columns))
print("Selected columns:", selected_columns)

display(table3_preview)

Table 3: Obesity and Anthropometric Risk Factors
Rows: 5
Columns found: 8
Selected columns: ['Reported Weight in Pounds (WEIGHT2)', 'Reported Height in Feet and Inches (HEIGHT3)', 'Computed Height in Inches (HTIN4)', 'Computed Height in Meters (HTM4)', 'Computed Weight in Kilograms (WTKG3)', 'Computed body mass index (_BMI5)', 'Computed body mass index categories (_BMI5CAT)', 'Overweight or obese calculated variable (_RFBMI5)']

,Reported Weight in Pounds (WEIGHT2),Reported Height in Feet and Inches (HEIGHT3),Computed Height in Inches (HTIN4),Computed Height in Meters (HTM4),Computed Weight in Kilograms (WTKG3),Computed body mass index (_BMI5),Computed body mass index categories (_BMI5CAT),Overweight or obese calculated variable (_RFBMI5)
0,131,504,64,163,5942,2249,Normal Weight,No
1,180,510,70,178,8165,2583,Overweight,Yes
2,195,606,78,198,8845,2253,Normal Weight,No
3,165,508,68,173,7484,2509,Overweight,Yes
4,130,508,68,173,5897,1977,Normal Weight,No

In [10]:
import pandas as pd

file_path = "decoded.csv"

table4_variables = [
    "EXERANY2", "_TOTINDA", "SMOKE100", "SMOKDAY2",
    "USENOW3", "ECIGNOW3", "LCSFIRST", "LCSNUMCG",
    "LASTSMK2", "STOPSMK2", "MENTCIGS", "MENTECIG",
    "HEATTBCO", "_SMOKER3", "_RFSMOK3", "_CURECI3",
    "LCSLAST_", "LCSNUMC_", "_LCSYSMK", "_PACKDAY",
    "_PACKYRS", "_LCSYQTS", "_LCSSMKG", "ALCDAY4",
    "AVEDRNK4", "DRNK3GE5", "MAXDRNKS", "DRNKANY6",
    "DROCDY4_", "_RFBING6", "_DRNKWK3", "_RFDRHV9",
    "SSBSUGR2", "SSBFRUT3", "MARIJAN1", "MARJSMOK",
    "MARJEAT", "MARJVAPE", "MARJDAB", "MARJOTHR",
    "USEMRJN4", "PREGNANT", "LCSCTSC1", "LCSSCNCR",
    "LCSCTWHN", "_LCSAGE", "_LCSELIG", "_LCSCTSN",
    "_LCSPSTF"
]

original_columns = pd.read_csv(file_path, nrows=0).columns.tolist()

selected_columns = [
    col for col in original_columns
    if any(
        col == var or col.endswith(f"({var})")
        for var in table4_variables
    )
]

table4_preview = pd.read_csv(
    file_path,
    usecols=selected_columns,
    nrows=5,
    dtype=str,
    encoding="utf-8-sig"
)

print("Table 4: Behavioral and Lifestyle Factors")
print("Rows:", len(table4_preview))
print("Columns found:", len(selected_columns))
print("Selected columns:", selected_columns)

display(table4_preview)

Table 4: Behavioral and Lifestyle Factors
Rows: 5
Columns found: 49
Selected columns: ['Exercise in Past 30 Days (EXERANY2)', 'Pregnancy Status (PREGNANT)', 'Smoked at Least 100 Cigarettes (SMOKE100)', 'Frequency of Days Now Smoking (SMOKDAY2)', 'Use of Smokeless Tobacco Products (USENOW3)', 'Do you now use e-cigarettes, or vaping products every day, some days, or not at all? (ECIGNOW3)', 'How old when you first started smoking? (LCSFIRST)', 'On average, how many cigarettes do you smoke each day? (LCSNUMCG)', 'Did you have a CT or CAT scan? (LCSCTSC1)', 'Were any CT or CAT scans done to check for lung cancer? (LCSSCNCR)', 'When did you have your most recent CT or CAT scan? (LCSCTWHN)', 'Days in past 30 had alcoholic beverage (ALCDAY4)', 'Avg alcoholic drinks per day in past 30 (AVEDRNK4)', 'Binge Drinking (DRNK3GE5)', 'Most drinks on single occasion past 30 days (MAXDRNKS)', 'During the past 30 days, on how many days did you use marijuana or hashish? (MARIJAN1)', 'Did you smoke marijuana or cannabis? (MARJSMOK)', 'Did you eat marijuana or cannabis? (MARJEAT)', 'Did you vape marijuana or cannabis? (MARJVAPE)', 'Did you dab marijuana or cannabis? (MARJDAB)', 'Did you use marijuana or cannabis some other way? (MARJOTHR)', 'USEMRJN4', 'Interval Since Last Smoked (LASTSMK2)', 'Stopped Smoking in past 12 months (STOPSMK2)', 'Do you usually smoke menthol cigarettes? (MENTCIGS)', 'Do you usually use menthol e-cigarettes? (MENTECIG)', 'Have you heard of heated tobacco products? (HEATTBCO)', 'How often did you drink regular soda or pop that contains sugar? (SSBSUGR2)', 'How often did you drink sugar-sweetened drinks? (SSBFRUT3)', 'Leisure Time Physical Activity Calculated Variable (_TOTINDA)', 'Computed Smoking Status (_SMOKER3)', 'Current Smoking Calculated Variable (_RFSMOK3)', 'Current E-cigarette User Calculated Variable (_CURECI3)', 'How old when you last smoked? (LCSLAST_)', 'On average, how many cigarettes do you smoke each day? (LCSNUMC_)', 'Lung Cancer Screening Age Groups (_LCSAGE)', 'Number of years smoked cigarettes (_LCSYSMK)', 'Number of packs of cigarettes smoked per day (_PACKDAY)', 'Years smoked reported packs per day (_PACKYRS)', 'Number of years since quit smoking cigarettes (_LCSYQTS)', 'LCS Smoking Group (_LCSSMKG)', 'USPSTF eligibility for Screening (_LCSELIG)', 'Had Chest CT Scan for Lung Cancer (_LCSCTSN)', 'Meet USPSTF Lung Cancer Screening Guidelines (_LCSPSTF)', 'Drink any alcoholic beverages in past 30 days (DRNKANY6)', 'Computed drink-occasions-per-day (DROCDY4_)', 'Binge Drinking Calculated Variable (_RFBING6)', 'Computed number of drinks of alcohol beverages per week (_DRNKWK3)', 'Heavy Alcohol Consumption  Calculated Variable (_RFDRHV9)']

,Exercise in Past 30 Days (EXERANY2),Pregnancy Status (PREGNANT),Smoked at Least 100 Cigarettes (SMOKE100),Frequency of Days Now Smoking (SMOKDAY2),Use of Smokeless Tobacco Products (USENOW3),"Do you now use e-cigarettes, or vaping products every day, some days, or not at all? (ECIGNOW3)",How old when you first started smoking? (LCSFIRST),"On average, how many cigarettes do you smoke each day? (LCSNUMCG)",Did you have a CT or CAT scan? (LCSCTSC1),Were any CT or CAT scans done to check for lung cancer? (LCSSCNCR),...,Number of years since quit smoking cigarettes (_LCSYQTS),LCS Smoking Group (_LCSSMKG),USPSTF eligibility for Screening (_LCSELIG),Had Chest CT Scan for Lung Cancer (_LCSCTSN),Meet USPSTF Lung Cancer Screening Guidelines (_LCSPSTF),Drink any alcoholic beverages in past 30 days (DRNKANY6),Computed drink-occasions-per-day (DROCDY4_),Binge Drinking Calculated Variable (_RFBING6),Computed number of drinks of alcohol beverages per week (_DRNKWK3),Heavy Alcohol Consumption Calculated Variable (_RFDRHV9)
0,Yes,NaN,No - Go to Section 11.03 USENOW3,NaN,Not at all,Never used e-cigarettes in your entire life,NaN,NaN,Yes,Don't know/Not sure - Go to next section,...,NaN,Never smoker,Do Not Meet USPSTF Eligibility Criteria,NaN,"Not Eligible, Don't know/Not sure, Refused, or...",No,5.40E-79,No,5.40E-79,No
1,Yes,NaN,Yes,Not at all,Not at all,Never used e-cigarettes in your entire life,25,20,No - Go to next section,NaN,...,53,"Former smoker, < 20 Pack Years",Do Not Meet USPSTF Eligibility Criteria,Never had a Chest CT Scan,"Not Eligible, Don't know/Not sure, Refused, or...",No,5.40E-79,No,5.40E-79,No
2,Yes,NaN,Yes,Every day,Not at all,Never used e-cigarettes in your entire life,14,15,No - Go to next section,NaN,...,NaN,"Current smoker, 20+ Pack Years",Meet USPSTF Eligibility Criteria,Never had a Chest CT Scan,Do Not Meet USPSTF Guidelines,Yes,100,Yes,1400,No
3,Yes,NaN,No - Go to Section 11.03 USENOW3,NaN,Not at all,Never used e-cigarettes in your entire life,NaN,NaN,Yes,Don't know/Not sure - Go to next section,...,NaN,Never smoker,Do Not Meet USPSTF Eligibility Criteria,NaN,"Not Eligible, Don't know/Not sure, Refused, or...",No,5.40E-79,No,5.40E-79,No
4,No,NaN,No - Go to Section 11.03 USENOW3,NaN,Not at all,Used them in the past but do not currently use...,NaN,NaN,Yes,No - Go to next section,...,NaN,Never smoker,Do Not Meet USPSTF Eligibility Criteria,Had Chest CT Scan for Other Reason,"Not Eligible, Don't know/Not sure, Refused, or...",No,5.40E-79,No,5.40E-79,No

In [11]:
import pandas as pd

file_path = "decoded.csv"

table5_variables = [
    "MARITAL", "EDUCA", "_EDUCAG", "RENTHOM1", "VETERAN3",
    "EMPLOY1", "CHILDREN", "_CHLDCNT", "INCOME3", "_INCOMG1",
    "NUMADULT", "HHADULT", "NUMHHOL4", "NUMPHON4", "CPDEMO1C",
    "FOODSTMP", "SDHFOOD1", "SDHBILLS", "SDHUTILS", "SDHEMPLY",
    "SDHTRNSP", "HOWSAFE1", "ACEDEPRS", "ACEDRINK", "ACEDRUGS",
    "ACEPRISN", "ACEDIVRC", "ACEPUNCH", "ACEHURT1", "ACESWEAR",
    "ACETOUCH", "ACETTHEM", "ACEHVSEX", "ACEADSAF", "ACEADNED",
    "CAREGIV1", "CRGVREL5", "CRGVPRB4", "CRGVALZD", "CRGVNURS",
    "CRGVPER2", "CRGVHOU2", "CRGVHRS2", "CRGVLNG2", "FIREARM5",
    "GUNLOAD", "LOADULK2"
]

original_columns = pd.read_csv(file_path, nrows=0).columns.tolist()

selected_columns = [
    col for col in original_columns
    if any(
        col == var or col.endswith(f"({var})")
        for var in table5_variables
    )
]

table5_preview = pd.read_csv(
    file_path,
    usecols=selected_columns,
    nrows=5,
    dtype=str,
    encoding="utf-8-sig"
)

print("Table 5: Socioeconomic and Household Variables")
print("Rows:", len(table5_preview))
print("Columns found:", len(selected_columns))
print("Selected columns:", selected_columns)

display(table5_preview)

Table 5: Socioeconomic and Household Variables
Rows: 5
Columns found: 47
Selected columns: ['Number of Adults in Household (NUMADULT)', 'Number of Adults in Household (HHADULT)', 'Marital Status (MARITAL)', 'Education Level (EDUCA)', 'Own or Rent Home (RENTHOM1)', 'Household Landline Telephones (NUMHHOL4)', 'Residential Landline Phones (NUMPHON4)', 'Do you have a cell phone for your personal use? (CPDEMO1C)', 'Are You A Veteran (VETERAN3)', 'Employment Status (EMPLOY1)', 'Number of Children in Household (CHILDREN)', 'Income Level (INCOME3)', 'Provided regular care for family or friend (CAREGIV1)', 'Relationship Of Person To Whom You Are Giving Care? (CRGVREL5)', 'What Is The Main Health Problem, Illness, Disability For Care For Person? (CRGVPRB4)', "Does Person Being Cared For Have Alzheimer's Disease? (CRGVALZD)", 'Help with Nursing or Medical Tasks (CRGVNURS)', 'Managed personal care (CRGVPER2)', 'Managed household tasks (CRGVHOU2)', 'How Many Hours Do You Provide Care For Person? (CRGVHRS2)', 'How Long Provided Care For Person. (CRGVLNG2)', 'Live With Anyone Depressed, Mentally Ill, Or Suicidal? (ACEDEPRS)', 'Live With a Problem Drinker/Alcoholic? (ACEDRINK)', 'Live With Anyone Who Used Illegal Drugs or Abused Prescriptions? (ACEDRUGS)', 'Live With Anyone Who Served TIme in Prison or Jail? (ACEPRISN)', 'Were Your Parents Divorced/Seperated? (ACEDIVRC)', 'How Often Did Your Parents Beat Each Other Up? (ACEPUNCH)', 'How Often Did A Parent Physically Hurt You In Any Way? (ACEHURT1)', 'How Often Did A Parent Swear At You? (ACESWEAR)', 'How Often Did Anyone Ever Touch You Sexually? (ACETOUCH)', 'How Often Did Anyone Make You Touch Them Sexually? (ACETTHEM)', 'How Often Did Anyone Ever Force You to Have Sex? (ACEHVSEX)', 'Did an adult make you feel safe and protected (ACEADSAF)', 'Did an adult make sure basic needs were met (ACEADNED)', 'Have you lost employment or had hours reduced? (SDHEMPLY)', 'During the past 12 months have you received food stamps (FOODSTMP)', "How often did the food that you bought not last, and you didn't have money to get more? (SDHFOOD1)", 'Were you not able to pay your bills? (SDHBILLS)', 'Were you not able to pay utility bills or threatened to lose service? (SDHUTILS)', 'Has a lack of reliable transportation kept you from appointments, meetings, work, or getting things needed (SDHTRNSP)', 'Neighborhood Safe From Crime (HOWSAFE1)', 'Any Firearms in Home (FIREARM5)', 'Any Firearms Loaded (GUNLOAD)', 'Any Loaded Firearms Also Unlocked (LOADULK2)', 'Computed number of children in household (_CHLDCNT)', 'Computed level of education completed categories (_EDUCAG)', 'Computed income categories (_INCOMG1)']

,Number of Adults in Household (NUMADULT),Number of Adults in Household (HHADULT),Marital Status (MARITAL),Education Level (EDUCA),Own or Rent Home (RENTHOM1),Household Landline Telephones (NUMHHOL4),Residential Landline Phones (NUMPHON4),Do you have a cell phone for your personal use? (CPDEMO1C),Are You A Veteran (VETERAN3),Employment Status (EMPLOY1),...,Were you not able to pay your bills? (SDHBILLS),Were you not able to pay utility bills or threatened to lose service? (SDHUTILS),"Has a lack of reliable transportation kept you from appointments, meetings, work, or getting things needed (SDHTRNSP)",Neighborhood Safe From Crime (HOWSAFE1),Any Firearms in Home (FIREARM5),Any Firearms Loaded (GUNLOAD),Any Loaded Firearms Also Unlocked (LOADULK2),Computed number of children in household (_CHLDCNT),Computed level of education completed categories (_EDUCAG),Computed income categories (_INCOMG1)
0,Number of adults in the household - Go to LL.0...,NaN,Widowed,Grade 12 or GED (High school graduate),Own,No - Go to Section 07.11 CPDEMO1C,NaN,1,No,Retired,...,No,No,No,Extremely safe,NaN,NaN,NaN,No children in household,Graduated High School,Don't know/Not sure/Missing
1,Number of adults in the household - Go to LL.0...,NaN,Married,College 4 years or more (College graduate),Own,No - Go to Section 07.11 CPDEMO1C,NaN,1,Yes,Retired,...,No,No,No,Extremely safe,NaN,NaN,NaN,No children in household,Graduated from College or Technical School,"$200,000 or more"
2,Number of adults in the household - Go to LL.0...,NaN,A member of an unmarried couple,College 1 year to 3 years (Some college or tec...,Own,No - Go to Section 07.11 CPDEMO1C,NaN,NaN,Yes,Employed for wages,...,No,No,No,Extremely safe,NaN,NaN,NaN,No children in household,Attended College or Technical School,Don't know/Not sure/Missing
3,Number of adults in the household - Go to LL.0...,NaN,Married,College 4 years or more (College graduate),Own,No - Go to Section 07.11 CPDEMO1C,NaN,1,No,Retired,...,No,No,No,Safe,NaN,NaN,NaN,No children in household,Graduated from College or Technical School,"$35,000 to < $50,000"
4,Number of adults in the household - Go to LL.0...,NaN,Never married,College 1 year to 3 years (Some college or tec...,Own,No - Go to Section 07.11 CPDEMO1C,NaN,1,No,Unable to work,...,No,No,Yes,Extremely safe,NaN,NaN,NaN,No children in household,Attended College or Technical School,"$15,000 to < $25,000"

In [12]:
import pandas as pd

file_path = "decoded.csv"

table6_variables = [
    "PRIMINS2", "PERSDOC3", "MEDCOST1", "CHECKUP1",
    "_HLTHPL2", "_HCVU654", "LASTDEN4", "RMVTETH4",
    "_EXTETH3", "_ALTETH3", "_DENVST3", "PDIABTS1",
    "INSULIN1", "CHKHEMO3", "EYEEXAM1", "DIABEYE1",
    "DIABEDU1", "FEETSORE", "ARTHEXER", "FLUSHOT7",
    "FLSHTMY3", "IMFVPLA5", "PNEUVAC4", "_FLSHOT7",
    "_PNEUMO3", "SHINGLE2", "HPVADVC4", "HPVADSH1",
    "TETANUS1", "HADMAM", "HOWLONG", "_RFMAM23",
    "_MAM402Y", "CERVSCRN", "CRVCLCNC", "CRVCLPAP",
    "CRVCLHPV", "HADHYST2", "_CRVSCRN", "_RFPAP37",
    "_HPV5YR1", "_PAPHPV1", "HADSIGM4", "COLNSIGM",
    "COLNTES1", "SIGMTES1", "LASTSIG4", "COLNCNCR",
    "VIRCOLO1", "VCLNTES2", "SMALSTOL", "STOLTEST",
    "STOOLDN2", "BLDSTFIT", "SDNATES1", "_HADCOLN",
    "_CLNSCP2", "_HADSIGM", "_SGMSCP2", "_SGMS102",
    "_RFBLDS6", "_STOLDN2", "_VIRCOL2", "_SBONTI2",
    "_CRCREC3", "HIVTST7", "HIVTSTD3", "HIVRISK5",
    "_AIDTST4", "PSATEST1", "PSATIME1", "PCPSARS2",
    "PSASUGS1", "PCSTALK2", "CSRVDOC1", "CSRVSUM",
    "CSRVRTRN", "CSRVINST", "CSRVINSR", "CSRVDEIN",
    "CSRVCLIN", "CSRVPAIN", "CSRVCTL2"
]

original_columns = pd.read_csv(file_path, nrows=0).columns.tolist()

selected_columns = [
    col for col in original_columns
    if any(
        col == var or col.endswith(f"({var})")
        for var in table6_variables
    )
]

table6_preview = pd.read_csv(
    file_path,
    usecols=selected_columns,
    nrows=5,
    dtype=str,
    encoding="utf-8-sig"
)

print("Table 6: Healthcare Access and Utilization")
print("Rows:", len(table6_preview))
print("Columns found:", len(selected_columns))
print("Selected columns:", selected_columns)

display(table6_preview)

Table 6: Healthcare Access and Utilization
Rows: 5
Columns found: 83
Selected columns: ['What is Your Current Primary Source of Health Care Coverage? (PRIMINS2)', 'Have Personal Health Care Provider? (PERSDOC3)', 'Could Not Afford To See Doctor (MEDCOST1)', 'Length of time since last routine checkup (CHECKUP1)', 'Last Visited Dentist or Dental Clinic (LASTDEN4)', 'Number of Permanent Teeth Removed (RMVTETH4)', 'Have You Ever Had a Mammogram (HADMAM)', 'How Long since Last Mammogram (HOWLONG)', 'Have you ever had a cervical cancer screening test? (CERVSCRN)', 'Time since last cervical cancer screening test (CRVCLCNC)', 'Have a PAP test and recent cervical cancer screening (CRVCLPAP)', 'Have an H.P.V. test and recent cervical cancer screening (CRVCLHPV)', 'Had Hysterectomy (HADHYST2)', 'Ever Had Sigmoidoscopy/Colonoscopy (HADSIGM4)', 'Ever had a colonoscopy, sigmoidoscopy, or both (COLNSIGM)', 'How long since you had colonoscopy (COLNTES1)', 'How long since you had sigmoidoscopy (SIGMTES1)', 'Time Since Last Sigmoidoscopy/Colonoscopy (LASTSIG4)', 'Ever had any other kind of test for colorectal cancer (COLNCNCR)', 'Ever had a virtual colonoscopy (VIRCOLO1)', 'How long since you had  virtual colonoscopy (VCLNTES2)', 'Ever had stool test? (SMALSTOL)', 'How long since you had stool test? (STOLTEST)', 'Ever had stool DNA test? (STOOLDN2)', 'Was test part of Cologuard test? (BLDSTFIT)', 'How long since you had stool DNA (SDNATES1)', 'Adult flu shot/spray past 12 mos (FLUSHOT7)', 'When did you receive your most recent seasonal flu shot/spray? (FLSHTMY3)', 'Where did you get your last flu shot/vaccine? (IMFVPLA5)', 'Pneumonia shot ever (PNEUVAC4)', 'Ever tested H.I.V. (HIVTST7)', 'Month and Year of Last HIV Test (HIVTSTD3)', 'Do Any High Risk Situations Apply (HIVRISK5)', 'When was your last blood test for high blood sugar? (PDIABTS1)', 'Now Taking Insulin (INSULIN1)', 'Times Checked for Glycosylated Hemoglobin (CHKHEMO3)', 'Last Eye Exam Where Pupils Were Dilated (EYEEXAM1)', 'When was the last time a they took a photo of the back of your eye? (DIABEYE1)', 'When was the last time you took a course or class in how to manage your diabetes? (DIABEDU1)', 'Ever Had Feet Sores or Irritations Lasting More Than Four Weeks (FEETSORE)', 'Dr. Suggest Use of Physical Activity or Exercise for Arthritis or Joint Symptoms (ARTHEXER)', 'Have you ever had the shingles or zoster vaccine? (SHINGLE2)', 'Have you ever had an H.P.V. vaccination? (HPVADVC4)', 'How many HPV shots did you receive? (HPVADSH1)', 'Received Tetanus Shot Since 2005? (TETANUS1)', 'What Type of Doctor Provides Majority of Your Care (CSRVDOC1)', 'Did You Receive a Summary of Cancer Treatments Received (CSRVSUM)', 'Ever Receive Instructions From A Doctor For Follow-Up Check-Ups (CSRVRTRN)', 'Instructions Written or Printed (CSRVINST)', 'Did Health Insurance Pay For All Of Your Cancer Treatment (CSRVINSR)', 'Ever Denied Insurance Coverage Because Of Your Cancer? (CSRVDEIN)', 'Participate In Clinical Trial As Part Of Cancer Treatment? (CSRVCLIN)', 'Currently Have Physical Pain From Cancer Or Treatment? (CSRVPAIN)', 'Is Pain Under Control? (CSRVCTL2)', 'Ever Had PSA Test (PSATEST1)', 'Time Since Most Recent PSA Test (PSATIME1)', 'What was the MAIN reason you had this PSA test? (PCPSARS2)', 'Who first suggested this P.S.A. test? (PSASUGS1)', 'Did you talk about the advantages or disadvantages of P.S.A. test (PCSTALK2)', 'Have any health insurance (_HLTHPL2)', 'Respondents aged 18-64 with health insurance (_HCVU654)', 'Adults aged 18+ that have had permanent teeth extracted (_EXTETH3)', 'Adults aged 65+ who have had all their natural teeth extracted (_ALTETH3)', 'Adults that have visited a dentist, dental hygenist or dental clinic within the past year (_DENVST3)', 'Women respondents aged 40+ who have had a mammogram in the past two years (_RFMAM23)', 'Women respondents aged 40-74 that have had a mammogram in the past two years (_MAM402Y)', 'Female respondents that have had a cervical screening test (_CRVSCRN)', 'Female respondents with and intact cervix, aged 21-65, who have had a pap test in the past three years (_RFPAP37)', 'Female respondents with and intact cervix, aged 30-65, who have had an HPV test in the past five years (_HPV5YR1)', 'Female respondents with an intact cervix, aged 21-65 that have had a pap test in last 3 years or aged 30-65 that have had an HPV test in last 5 years (_PAPHPV1)', 'Had colonoscopy calculated variable (_HADCOLN)', 'Respondents aged 45-75 who have had a colonoscopy within the past ten years (_CLNSCP2)', 'Had sigmoidoscopy calculated variable (_HADSIGM)', 'Respondents aged 45-75 who have had a sigmoidoscopy within the past five years (_SGMSCP2)', 'Respondents aged 45-75 who have had a sigmoidoscopy within the past ten years (_SGMS102)', 'Respondents aged 45-75 who have had a stool test within the past year (_RFBLDS6)', 'Respondents aged 45-75 who have had a stool DNA test within the past three years (_STOLDN2)', 'Respondents aged 45-75 who have had a virtual colonoscopy within the past five years (_VIRCOL2)', 'Respondents aged 45-75 who have had a sigmoidoscopy within the past ten years and a blood stool test in the past year (_SBONTI2)', 'Respondents aged 45-75 who have fully met the USPSTF recommendations (_CRCREC3)', 'Flu Shot Calculated Variable (_FLSHOT7)', 'Pneumonia Vaccination Calculated Variable (_PNEUMO3)', 'Ever been tested for HIV calculated variable (_AIDTST4)']

,What is Your Current Primary Source of Health Care Coverage? (PRIMINS2),Have Personal Health Care Provider? (PERSDOC3),Could Not Afford To See Doctor (MEDCOST1),Length of time since last routine checkup (CHECKUP1),Last Visited Dentist or Dental Clinic (LASTDEN4),Number of Permanent Teeth Removed (RMVTETH4),Have You Ever Had a Mammogram (HADMAM),How Long since Last Mammogram (HOWLONG),Have you ever had a cervical cancer screening test? (CERVSCRN),Time since last cervical cancer screening test (CRVCLCNC),...,Respondents aged 45-75 who have had a sigmoidoscopy within the past five years (_SGMSCP2),Respondents aged 45-75 who have had a sigmoidoscopy within the past ten years (_SGMS102),Respondents aged 45-75 who have had a stool test within the past year (_RFBLDS6),Respondents aged 45-75 who have had a stool DNA test within the past three years (_STOLDN2),Respondents aged 45-75 who have had a virtual colonoscopy within the past five years (_VIRCOL2),Respondents aged 45-75 who have had a sigmoidoscopy within the past ten years and a blood stool test in the past year (_SBONTI2),Respondents aged 45-75 who have fully met the USPSTF recommendations (_CRCREC3),Flu Shot Calculated Variable (_FLSHOT7),Pneumonia Vaccination Calculated Variable (_PNEUMO3),Ever been tested for HIV calculated variable (_AIDTST4)
0,Medicare,More than one,No,Within past year (anytime less than 12 months ...,Within the past year (anytime < 12 months ago),1 to 5,Yes,Within the past 2 years (1 year but less than ...,Yes,Within the past 2 years (1 year but less than ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,No,No
1,Medicare,"Yes, only one",No,Within past year (anytime less than 12 months ...,Within the past year (anytime < 12 months ago),1 to 5,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,No
2,A plan purchased through an employer or union ...,No,Yes,5 or more years ago,5 or more years ago,"6 or more, but not all",NaN,NaN,NaN,NaN,...,Have never had a sigmoidoscopy,Have never had a sigmoidoscopy,Have never had a blood stool test,Have never had a stool DNA test,Have never had a virtual colonoscopy,Never had either,Have never had any of the recommended CRC tests,NaN,NaN,No
3,Medicare,"Yes, only one",No,Within past year (anytime less than 12 months ...,Within the past year (anytime < 12 months ago),NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,No
4,Medicaid,"Yes, only one",No,Within past year (anytime less than 12 months ...,Within the past year (anytime < 12 months ago),1 to 5,NaN,NaN,NaN,NaN,...,Have never had a sigmoidoscopy,Have never had a sigmoidoscopy,Have never had a blood stool test,Have never had a stool DNA test,Have never had a virtual colonoscopy,Never had either,Have never had any of the recommended CRC tests,NaN,NaN,No

In [13]:
import pandas as pd

file_path = "decoded.csv"

table7_variables = [
    "GENHLTH", "PHYSHLTH", "MENTHLTH", "POORHLTH",
    "_RFHLTH", "_PHYS14D", "_MENT14D", "DEAF",
    "BLIND", "DECIDE", "DIFFWALK", "DIFFDRES",
    "DIFFALON", "CIMEMLO1", "CDWORRY", "CDDISCU1",
    "CDHOUS1", "CDSOCIA1", "LSATISFY", "EMTSUPRT",
    "SDLONELY"
]

child_variables = [
    "RCSGEND1", "RCSXBRTH", "RCSRLTN2", "CASTHDX2",
    "CASTHNO2", "_CHISPNC", "_CRACE1", "CAGEG",
    "_CLLCPWT"
]

original_columns = pd.read_csv(file_path, nrows=0).columns.tolist()

def find_columns(variables):
    return [
        col for col in original_columns
        if any(
            col == var or col.endswith(f"({var})")
            for var in variables
        )
    ]

table7_columns = find_columns(table7_variables)
child_columns = find_columns(child_variables)

table7_preview = pd.read_csv(
    file_path,
    usecols=table7_columns,
    nrows=5,
    dtype=str,
    encoding="utf-8-sig"
)

child_preview = pd.read_csv(
    file_path,
    usecols=child_columns,
    nrows=5,
    dtype=str,
    encoding="utf-8-sig"
)

print("Table 7: General Physical and Mental Health")
print("Rows:", len(table7_preview))
print("Columns found:", len(table7_columns))
print("Missing variables:", sorted(set(table7_variables) - {
    col.split("(")[-1].rstrip(")") if "(" in col else col
    for col in table7_columns
}))
display(table7_preview)

print("\nChild-focused variables — separate analysis")
print("Rows:", len(child_preview))
print("Columns found:", len(child_columns))
display(child_preview)

Table 7: General Physical and Mental Health
Rows: 5
Columns found: 21
Missing variables: []

,General Health (GENHLTH),Number of Days Physical Health Not Good (PHYSHLTH),Number of Days Mental Health Not Good (MENTHLTH),Poor Physical or Mental Health (POORHLTH),Are you deaf or do you have serious difficulty hearing? (DEAF),Blind or Difficulty seeing (BLIND),Difficulty Concentrating or Remembering (DECIDE),Difficulty Walking or Climbing Stairs (DIFFWALK),Difficulty Dressing or Bathing (DIFFDRES),Difficulty Doing Errands Alone (DIFFALON),...,Are you worried about these difficulties with thinking or memory? (CDWORRY),Have you discussed your difficulties with thinking with a health care provider? (CDDISCU1),Given up day-to-day chores due to difficulties with thinking or memory (CDHOUS1),Does difficulties with thinking or memory interfere with work or social activities (CDSOCIA1),Satisfaction with life (LSATISFY),How often get emotional support needed (EMTSUPRT),How often do you feel lonely? (SDLONELY),Adults with good or better health (_RFHLTH),Computed Physical Health Status (_PHYS14D),Computed Mental Health Status (_MENT14D)
0,Good,2,NaN,NaN,No,No,No,No,No,No,...,NaN,NaN,NaN,NaN,Very satisfied,Always,Never,Good or Better Health,1-13 days when physical health not good,Zero days when mental health not good
1,Excellent,NaN,NaN,NaN,No,No,No,No,No,No,...,NaN,NaN,NaN,NaN,Very satisfied,Always,Never,Good or Better Health,Zero days when physical health not good,Zero days when mental health not good
2,Very good,30,NaN,1,No,No,No,No,No,No,...,NaN,NaN,NaN,NaN,Very satisfied,Usually,Never,Good or Better Health,14+ days when physical health not good,Zero days when mental health not good
3,Excellent,NaN,NaN,NaN,Yes,No,No,No,No,No,...,NaN,NaN,NaN,NaN,Very satisfied,Always,Never,Good or Better Health,Zero days when physical health not good,Zero days when mental health not good
4,Good,NaN,NaN,NaN,Yes,No,No,Yes,No,Yes,...,NaN,NaN,NaN,NaN,Satisfied,Rarely,Always,Good or Better Health,Zero days when physical health not good,Zero days when mental health not good

Child-focused variables — separate analysis
Rows: 5
Columns found: 9

,RCSGEND1,RCSXBRTH,Relationship to child (RCSRLTN2),Hlth pro ever said child has asthma (CASTHDX2),Child still have asthma? (CASTHNO2),"Child Hispanic, Latino/a, or Spanish origin calculated variable (_CHISPNC)",Child Non-Hispanic Race including Multiracial (_CRACE1),Four level child age (CAGEG),Final child weight: Land-line and Cell-Phone data (_CLLCPWT)
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
tables = [
    table1_variables,
    table2_variables,
    table3_variables,
    table4_variables,
    table5_variables,
    table6_variables,
    table7_variables
]

total_columns = sum(len(table) for table in tables)

unique_columns = set(
    variable
    for table in tables
    for variable in table
)

print("Total columns across 7 tables:", total_columns)
print("Unique columns without duplicates:", len(unique_columns))
print("Duplicate columns:", total_columns - len(unique_columns))

Total columns across 7 tables: 267
Unique columns without duplicates: 267
Duplicate columns: 0

In [15]:
import pandas as pd

file_path = "decoded.csv"

all_variables = (
    table1_variables
    + table2_variables
    + table3_variables
    + table4_variables
    + table5_variables
    + table6_variables
    + table7_variables
)

original_columns = pd.read_csv(file_path, nrows=0).columns.tolist()

found_variables = [
    var for var in all_variables
    if any(
        col == var or col.endswith(f"({var})")
        for col in original_columns
    )
]

missing_variables = [
    var for var in all_variables
    if var not in found_variables
]

print("Total requested variables:", len(all_variables))
print("Variables found in source:", len(found_variables))
print("Variables not found:", len(missing_variables))
print("Missing variables:", missing_variables)

Total requested variables: 267
Variables found in source: 267
Variables not found: 0
Missing variables: []

In [16]:
import os

print("Current folder:", os.getcwd())
print("\nFiles in current folder:")

for file in os.listdir():
    if file.endswith(".csv"):
        print(file)

Current folder: c:\Users\USER\OneDrive\Desktop\BRFSS

Files in current folder:
decoded.csv

In [17]:
import pandas as pd

total_rows = sum(
    len(chunk)
    for chunk in pd.read_csv(
        "decoded.csv",
        usecols=[0],
        chunksize=50000
    )
)

print("Total Rows in original dataset:", total_rows)

Total Rows in original dataset: 457670

In [18]:
table1_variables = [
    "DIABETE4",
    "CVDINFR4",
    "CVDCRHD4",
    "CVDSTRK3",
    "CHCKDNY2",
    "ADDEPEV3",
    "CHCSCNC1",
    "CHCOCNC1",
    "HAVARTH4",
    "CHCCOPD3",
    "ASTHMA3",
    "ASTHNOW"
]

In [19]:
table2_variables = [
    "_STATE",
    "SEXVAR",
    "_AGE80",
    "_RACE",
    "EDUCA",
    "INCOME3",
    "EMPLOY1",
    "MARITAL",
    "SEQNO",
    "_PSU",
    "_STSTR",
    "_LLCPWT"
]

In [20]:
table3_variables = [
    "HTM4",
    "WTKG3",
    "_BMI5",
    "_BMI5CAT",
    "_RFBMI5"
]

In [21]:
table4_variables = [
    "EXERANY2",
    "SMOKE100",
    "SMOKDAY2",
    "USENOW3",
    "ECIGNOW3",
    "LCSFIRST",
    "LCSLAST",
    "LCSNUMCG",
    "_LCSYQTS",
    "_LCSSMKG",
    "_PACKDAY",
    "_PACKYRS",
    "DRNKANY6",
    "DROCDY4_",
    "_RFBING6",
    "_DRNKWK3",
    "_RFDRHV9"
]

In [22]:
table5_variables = [
    "MARITAL",
    "EDUCA",
    "EMPLOY1",
    "INCOME3",
    "RENTHOM1",
    "SDHBILLS",
    "SDHUTILS",
    "SDHTRNSP",
    "_CHLDCNT",
    "VETERAN3",
    "HOWSAFE1"
]

In [23]:
table6_variables = [
    "PRIMINS2",
    "PERSDOC3",
    "MEDCOST1",
    "CHECKUP1",
    "LASTDEN4",
    "RMVTETH4",
    "_FLSHOT7",
    "_PNEUMO3"
]

In [24]:
table7_variables = [
    "GENHLTH",
    "PHYSHLTH",
    "MENTHLTH",
    "POORHLTH",
    "DIFFWALK",
    "DIFFDRES",
    "DIFFALON",
    "DECIDE",
    "LSATISFY",
    "EMTSUPRT",
    "SDLONELY",
    "_PHYS14D",
    "_MENT14D"
]

In [25]:
import pandas as pd
from pathlib import Path

# 1. Set the source file path
file_path = Path(
    r"C:\Users\USER\OneDrive\Desktop\BRFSS\decoded.csv"
)

# 2. Load the original dataset
df = pd.read_csv(file_path, low_memory=False)

print("Original dataset shape:", df.shape)

# 3. Combine all selected variable codes from Tables 1–7
all_selected_variables = list(dict.fromkeys(
    table1_variables
    + table2_variables
    + table3_variables
    + table4_variables
    + table5_variables
    + table6_variables
    + table7_variables
))

# 4. Match selected codes to actual dataset column names
# Example: "Diabetes status (DIABETE4)"
original_columns = df.columns.tolist()

selected_columns = [
    col for col in original_columns
    if any(
        col.strip() == var
        or col.strip().endswith(f"({var})")
        for var in all_selected_variables
    )
]

# 5. Create the combined analytical dataset
final_df = df[selected_columns].copy()

# 6. Display the dataset
display(final_df.head())

print("\nOriginal dataset shape:", df.shape)
print("Final dataset shape:", final_df.shape)
print("Number of selected variables:", len(selected_columns))

# 7. Inspect columns and data types
final_df.info()

# 8. Display all selected column names
for col in selected_columns:
    print(col)

Original dataset shape: (457670, 301)

,State FIPS Code (_STATE),Annual Sequence Number (SEQNO),Primary Sampling Unit (_PSU),Sex of Respondent (SEXVAR),General Health (GENHLTH),Number of Days Physical Health Not Good (PHYSHLTH),Number of Days Mental Health Not Good (MENTHLTH),Poor Physical or Mental Health (POORHLTH),What is Your Current Primary Source of Health Care Coverage? (PRIMINS2),Have Personal Health Care Provider? (PERSDOC3),...,Years smoked reported packs per day (_PACKYRS),Number of years since quit smoking cigarettes (_LCSYQTS),LCS Smoking Group (_LCSSMKG),Drink any alcoholic beverages in past 30 days (DRNKANY6),Computed drink-occasions-per-day (DROCDY4_),Binge Drinking Calculated Variable (_RFBING6),Computed number of drinks of alcohol beverages per week (_DRNKWK3),Heavy Alcohol Consumption Calculated Variable (_RFDRHV9),Flu Shot Calculated Variable (_FLSHOT7),Pneumonia Vaccination Calculated Variable (_PNEUMO3)
0,Alabama,2024000001,2024000001,Female,Good,2,NaN,NaN,Medicare,More than one,...,NaN,NaN,Never smoker,No,5.40E-79,No,5.40E-79,No,Yes,No
1,Alabama,2024000002,2024000002,Male,Excellent,NaN,NaN,NaN,Medicare,"Yes, only one",...,2.0,53.0,"Former smoker, < 20 Pack Years",No,5.40E-79,No,5.40E-79,No,Yes,Yes
2,Alabama,2024000003,2024000003,Male,Very good,30,NaN,1,A plan purchased through an employer or union ...,No,...,34.0,NaN,"Current smoker, 20+ Pack Years",Yes,100,Yes,1400,No,NaN,NaN
3,Alabama,2024000004,2024000004,Male,Excellent,NaN,NaN,NaN,Medicare,"Yes, only one",...,NaN,NaN,Never smoker,No,5.40E-79,No,5.40E-79,No,Yes,Yes
4,Alabama,2024000005,2024000005,Male,Good,NaN,NaN,NaN,Medicaid,"Yes, only one",...,NaN,NaN,Never smoker,No,5.40E-79,No,5.40E-79,No,NaN,NaN

Original dataset shape: (457670, 301)
Final dataset shape: (457670, 73)
Number of selected variables: 73
<class 'pandas.DataFrame'>
RangeIndex: 457670 entries, 0 to 457669
Data columns (total 73 columns):
 #   Column                                                                                                                 Non-Null Count   Dtype
---  ------                                                                                                                 --------------   -----
 0   State FIPS Code (_STATE)                                                                                               457670 non-null  str
 1   Annual Sequence Number (SEQNO)                                                                                         457670 non-null  int64
 2   Primary Sampling Unit (_PSU)                                                                                           457670 non-null  int64
 3   Sex of Respondent (SEXVAR)                                                                                             457670 non-null  str
 4   General Health (GENHLTH)                                                                                               457665 non-null  str
 5   Number of Days Physical Health Not Good (PHYSHLTH)                                                                     190089 non-null  str
 6   Number of Days Mental Health Not Good (MENTHLTH)                                                                       187758 non-null  str
 7   Poor Physical or Mental Health (POORHLTH)                                                                              131705 non-null  str
 8   What is Your Current Primary Source of Health Care Coverage? (PRIMINS2)                                                457667 non-null  str
 9   Have Personal Health Care Provider? (PERSDOC3)                                                                         457667 non-null  str
 10  Could Not Afford To See Doctor (MEDCOST1)                                                                              457664 non-null  str
 11  Length of time since last routine checkup (CHECKUP1)                                                                   457668 non-null  str
 12  Exercise in Past 30 Days (EXERANY2)                                                                                    457667 non-null  str
 13  Last Visited Dentist or Dental Clinic (LASTDEN4)                                                                       457668 non-null  str
 14  Number of Permanent Teeth Removed (RMVTETH4)                                                                           216436 non-null  str
 15  Ever Diagnosed with Heart Attack (CVDINFR4)                                                                            457668 non-null  str
 16  Ever Diagnosed with Angina or Coronary Heart Disease (CVDCRHD4)                                                        457667 non-null  str
 17  Ever Diagnosed with a Stroke (CVDSTRK3)                                                                                457667 non-null  str
 18  Ever Told Had Asthma (ASTHMA3)                                                                                         457667 non-null  str
 19  Still Have Asthma (ASTHNOW)                                                                                            72037 non-null   str
 20  (Ever told) (you had) skin cancer that is not melanoma? (CHCSCNC1)                                                     457664 non-null  str
 21  (Ever told) (you had)  melanoma or any other types of cancer? (CHCOCNC1)                                               457665 non-null  str
 22  Ever told you had C.O.P.D. emphysema or chronic bronchitis? (CHCCOPD3)                                                 457663 non-null  str
 23  (Ever told) you had a depressive disorder (ADDEPEV3)                                                                   457665 non-null  str
 24  Ever told you have kidney disease? (CHCKDNY2)                                                                          457664 non-null  str
 25  Told Had Arthritis (HAVARTH4)                                                                                          457665 non-null  str
 26  (Ever told) you had diabetes (DIABETE4)                                                                                457666 non-null  str
 27  Marital Status (MARITAL)                                                                                               457661 non-null  str
 28  Education Level (EDUCA)                                                                                                457663 non-null  str
 29  Own or Rent Home (RENTHOM1)                                                                                            457662 non-null  str
 30  Are You A Veteran (VETERAN3)                                                                                           456435 non-null  str
 31  Employment Status (EMPLOY1)                                                                                            454367 non-null  str
 32  Income Level (INCOME3)                                                                                                 448401 non-null  str
 33  Difficulty Concentrating or Remembering (DECIDE)                                                                       440229 non-null  str
 34  Difficulty Walking or Climbing Stairs (DIFFWALK)                                                                       438998 non-null  str
 35  Difficulty Dressing or Bathing (DIFFDRES)                                                                              438211 non-null  str
 36  Difficulty Doing Errands Alone (DIFFALON)                                                                              437137 non-null  str
 37  Smoked at Least 100 Cigarettes (SMOKE100)                                                                              428810 non-null  str
 38  Frequency of Days Now Smoking (SMOKDAY2)                                                                               167076 non-null  str
 39  Use of Smokeless Tobacco Products (USENOW3)                                                                            428029 non-null  str
 40  Do you now use e-cigarettes, or vaping products every day, some days, or not at all? (ECIGNOW3)                        426994 non-null  str
 41  How old when you first started smoking? (LCSFIRST)                                                                     164110 non-null  str
 42  On average, how many cigarettes do you smoke each day? (LCSNUMCG)                                                      158047 non-null  str
 43  Satisfaction with life (LSATISFY)                                                                                      203764 non-null  str
 44  How often get emotional support needed (EMTSUPRT)                                                                      203462 non-null  str
 45  How often do you feel lonely? (SDLONELY)                                                                               203201 non-null  str
 46  Were you not able to pay your bills? (SDHBILLS)                                                                        202218 non-null  str
 47  Were you not able to pay utility bills or threatened to lose service? (SDHUTILS)                                       202008 non-null  str
 48  Has a lack of reliable transportation kept you from appointments, meetings, work, or getting things needed (SDHTRNSP)  201734 non-null  str
 49  Neighborhood Safe From Crime (HOWSAFE1)                                                                                201389 non-null  str
 50  Sample Design Stratification Variable (_STSTR)                                                                         457670 non-null  int64
 51  Final weight: Land-line and cell-phone data (_LLCPWT)                                                                  457670 non-null  float64
 52  Computed Physical Health Status (_PHYS14D)                                                                             457670 non-null  str
 53  Computed Mental Health Status (_MENT14D)                                                                               457670 non-null  str
 54  Computed Race-Ethnicity grouping (_RACE)                                                                               457670 non-null  str
 55  Imputed Age value collapsed above 80 (_AGE80)                                                                          457670 non-null  int64
 56  Computed Height in Meters (HTM4)                                                                                       433610 non-null  float64
 57  Computed Weight in Kilograms (WTKG3)                                                                                   421278 non-null  float64
 58  Computed body mass index (_BMI5)                                                                                       414633 non-null  float64
 59  Computed body mass index categories (_BMI5CAT)                                                                         414633 non-null  str
 60  Overweight or obese calculated variable (_RFBMI5)                                                                      457670 non-null  str
 61  Computed number of children in household (_CHLDCNT)                                                                    457669 non-null  str
 62  Number of packs of cigarettes smoked per day (_PACKDAY)                                                                152692 non-null  float64
 63  Years smoked reported packs per day (_PACKYRS)                                                                         147270 non-null  float64
 64  Number of years since quit smoking cigarettes (_LCSYQTS)                                                               120603 non-null  float64
 65  LCS Smoking Group (_LCSSMKG)                                                                                           406226 non-null  str
 66  Drink any alcoholic beverages in past 30 days (DRNKANY6)                                                               457670 non-null  str
 67  Computed drink-occasions-per-day (DROCDY4_)                                                                            457669 non-null  str
 68  Binge Drinking Calculated Variable (_RFBING6)                                                                          457670 non-null  str
 69  Computed number of drinks of alcohol beverages per week (_DRNKWK3)                                                     457670 non-null  str
 70  Heavy Alcohol Consumption  Calculated Variable (_RFDRHV9)                                                              457670 non-null  str
 71  Flu Shot Calculated Variable (_FLSHOT7)                                                                                179344 non-null  str
 72  Pneumonia Vaccination Calculated Variable (_PNEUMO3)                                                                   179344 non-null  str
dtypes: float64(7), int64(4), str(62)
memory usage: 545.4 MB
State FIPS Code (_STATE)
Annual Sequence Number (SEQNO)
Primary Sampling Unit (_PSU)
Sex of Respondent (SEXVAR)
General Health (GENHLTH)
Number of Days Physical Health Not Good (PHYSHLTH)
Number of Days Mental Health Not Good (MENTHLTH)
Poor Physical or Mental Health (POORHLTH)
What is Your Current Primary Source of Health Care Coverage? (PRIMINS2)
Have Personal Health Care Provider? (PERSDOC3)
Could Not Afford To See Doctor (MEDCOST1)
Length of time since last routine checkup (CHECKUP1)
Exercise in Past 30 Days (EXERANY2)
Last Visited Dentist or Dental Clinic (LASTDEN4)
Number of Permanent Teeth Removed (RMVTETH4)
Ever Diagnosed with Heart Attack (CVDINFR4)
Ever Diagnosed with Angina or Coronary Heart Disease (CVDCRHD4)
Ever Diagnosed with a Stroke (CVDSTRK3)
Ever Told Had Asthma (ASTHMA3)
Still Have Asthma (ASTHNOW)
(Ever told) (you had) skin cancer that is not melanoma? (CHCSCNC1)
(Ever told) (you had)  melanoma or any other types of cancer? (CHCOCNC1)
Ever told you had C.O.P.D. emphysema or chronic bronchitis? (CHCCOPD3)
(Ever told) you had a depressive disorder (ADDEPEV3)
Ever told you have kidney disease? (CHCKDNY2)
Told Had Arthritis (HAVARTH4)
(Ever told) you had diabetes (DIABETE4)
Marital Status (MARITAL)
Education Level (EDUCA)
Own or Rent Home (RENTHOM1)
Are You A Veteran (VETERAN3)
Employment Status (EMPLOY1)
Income Level (INCOME3)
Difficulty Concentrating or Remembering (DECIDE)
Difficulty Walking or Climbing Stairs (DIFFWALK)
Difficulty Dressing or Bathing (DIFFDRES)
Difficulty Doing Errands Alone (DIFFALON)
Smoked at Least 100 Cigarettes (SMOKE100)
Frequency of Days Now Smoking (SMOKDAY2)
Use of Smokeless Tobacco Products (USENOW3)
Do you now use e-cigarettes, or vaping products every day, some days, or not at all? (ECIGNOW3)
How old when you first started smoking? (LCSFIRST)
On average, how many cigarettes do you smoke each day? (LCSNUMCG)
Satisfaction with life (LSATISFY)
How often get emotional support needed (EMTSUPRT)
How often do you feel lonely? (SDLONELY)
Were you not able to pay your bills? (SDHBILLS)
Were you not able to pay utility bills or threatened to lose service? (SDHUTILS)
Has a lack of reliable transportation kept you from appointments, meetings, work, or getting things needed (SDHTRNSP)
Neighborhood Safe From Crime (HOWSAFE1)
Sample Design Stratification Variable (_STSTR)
Final weight: Land-line and cell-phone data (_LLCPWT)
Computed Physical Health Status (_PHYS14D)
Computed Mental Health Status (_MENT14D)
Computed Race-Ethnicity grouping (_RACE)
Imputed Age value collapsed above 80 (_AGE80)
Computed Height in Meters (HTM4)
Computed Weight in Kilograms (WTKG3)
Computed body mass index (_BMI5)
Computed body mass index categories (_BMI5CAT)
Overweight or obese calculated variable (_RFBMI5)
Computed number of children in household (_CHLDCNT)
Number of packs of cigarettes smoked per day (_PACKDAY)
Years smoked reported packs per day (_PACKYRS)
Number of years since quit smoking cigarettes (_LCSYQTS)
LCS Smoking Group (_LCSSMKG)
Drink any alcoholic beverages in past 30 days (DRNKANY6)
Computed drink-occasions-per-day (DROCDY4_)
Binge Drinking Calculated Variable (_RFBING6)
Computed number of drinks of alcohol beverages per week (_DRNKWK3)
Heavy Alcohol Consumption  Calculated Variable (_RFDRHV9)
Flu Shot Calculated Variable (_FLSHOT7)
Pneumonia Vaccination Calculated Variable (_PNEUMO3)

In [26]:
found_variables = {
    var
    for var in all_selected_variables
    if any(
        col.strip() == var
        or col.strip().endswith(f"({var})")
        for col in original_columns
    )
}

missing_variables = [
    var for var in all_selected_variables
    if var not in found_variables
]

print("Requested variables:", len(all_selected_variables))
print("Found variables:", len(found_variables))
print("Missing variables:", len(missing_variables))

print("\nMissing variable codes:")
print(missing_variables)

Requested variables: 74
Found variables: 73
Missing variables: 1

Missing variable codes:
['LCSLAST']

In [27]:
import pandas as pd
from IPython.display import display

# Create the final dataset from the selected columns
final_df = df[selected_columns].copy()

# Display dataset dimensions
print("Final Dataset Shape:", final_df.shape)
print("Total Rows:", final_df.shape[0])
print("Total Columns:", final_df.shape[1])

# Display all rows and all columns
with pd.option_context(
    "display.max_rows", None,
    "display.max_columns", None,
    "display.max_colwidth", None,
    "display.width", None
):
    display(final_df)

Final Dataset Shape: (457670, 73)
Total Rows: 457670
Total Columns: 73

KeyboardInterrupt:

In [30]:
# Display only the first 10 rows
display(final_df.head(10))

,State FIPS Code (_STATE),Annual Sequence Number (SEQNO),Primary Sampling Unit (_PSU),Sex of Respondent (SEXVAR),General Health (GENHLTH),Number of Days Physical Health Not Good (PHYSHLTH),Number of Days Mental Health Not Good (MENTHLTH),Poor Physical or Mental Health (POORHLTH),What is Your Current Primary Source of Health Care Coverage? (PRIMINS2),Have Personal Health Care Provider? (PERSDOC3),...,Years smoked reported packs per day (_PACKYRS),Number of years since quit smoking cigarettes (_LCSYQTS),LCS Smoking Group (_LCSSMKG),Drink any alcoholic beverages in past 30 days (DRNKANY6),Computed drink-occasions-per-day (DROCDY4_),Binge Drinking Calculated Variable (_RFBING6),Computed number of drinks of alcohol beverages per week (_DRNKWK3),Heavy Alcohol Consumption Calculated Variable (_RFDRHV9),Flu Shot Calculated Variable (_FLSHOT7),Pneumonia Vaccination Calculated Variable (_PNEUMO3)
0,Alabama,2024000001,2024000001,Female,Good,2,NaN,NaN,Medicare,More than one,...,NaN,NaN,Never smoker,No,5.40E-79,No,5.40E-79,No,Yes,No
1,Alabama,2024000002,2024000002,Male,Excellent,NaN,NaN,NaN,Medicare,"Yes, only one",...,2.000000e+00,53.0,"Former smoker, < 20 Pack Years",No,5.40E-79,No,5.40E-79,No,Yes,Yes
2,Alabama,2024000003,2024000003,Male,Very good,30,NaN,1,A plan purchased through an employer or union ...,No,...,3.400000e+01,NaN,"Current smoker, 20+ Pack Years",Yes,100,Yes,1400,No,NaN,NaN
3,Alabama,2024000004,2024000004,Male,Excellent,NaN,NaN,NaN,Medicare,"Yes, only one",...,NaN,NaN,Never smoker,No,5.40E-79,No,5.40E-79,No,Yes,Yes
4,Alabama,2024000005,2024000005,Male,Good,NaN,NaN,NaN,Medicaid,"Yes, only one",...,NaN,NaN,Never smoker,No,5.40E-79,No,5.40E-79,No,NaN,NaN
5,Alabama,2024000006,2024000006,Male,Good,7,NaN,NaN,A plan purchased through an employer or union ...,More than one,...,NaN,NaN,Never smoker,No,5.40E-79,No,5.40E-79,No,NaN,NaN
6,Alabama,2024000007,2024000007,Female,Fair,NaN,NaN,NaN,Medicare,"Yes, only one",...,NaN,NaN,Never smoker,No,5.40E-79,No,5.40E-79,No,No,Yes
7,Alabama,2024000008,2024000008,Female,Poor,30,NaN,NaN,Medicare,More than one,...,NaN,NaN,Never smoker,No,5.40E-79,No,5.40E-79,No,No,Yes
8,Alabama,2024000009,2024000009,Female,Good,5,NaN,NaN,Medicare,"Yes, only one",...,NaN,NaN,Never smoker,No,5.40E-79,No,5.40E-79,No,Yes,Yes
9,Alabama,2024000010,2024000010,Male,Fair,14,NaN,14,Medicare,More than one,...,5.400000e-79,80.0,"Former smoker, < 20 Pack Years",No,5.40E-79,No,5.40E-79,No,Yes,No

In [31]:
import pandas as pd

# Display all columns and the first 5 rows
with pd.option_context(
    "display.max_columns", None,
    "display.max_colwidth", None,
    "display.width", None
):
    display(final_df.head(5))

,State FIPS Code (_STATE),Annual Sequence Number (SEQNO),Primary Sampling Unit (_PSU),Sex of Respondent (SEXVAR),General Health (GENHLTH),Number of Days Physical Health Not Good (PHYSHLTH),Number of Days Mental Health Not Good (MENTHLTH),Poor Physical or Mental Health (POORHLTH),What is Your Current Primary Source of Health Care Coverage? (PRIMINS2),Have Personal Health Care Provider? (PERSDOC3),Could Not Afford To See Doctor (MEDCOST1),Length of time since last routine checkup (CHECKUP1),Exercise in Past 30 Days (EXERANY2),Last Visited Dentist or Dental Clinic (LASTDEN4),Number of Permanent Teeth Removed (RMVTETH4),Ever Diagnosed with Heart Attack (CVDINFR4),Ever Diagnosed with Angina or Coronary Heart Disease (CVDCRHD4),Ever Diagnosed with a Stroke (CVDSTRK3),Ever Told Had Asthma (ASTHMA3),Still Have Asthma (ASTHNOW),(Ever told) (you had) skin cancer that is not melanoma? (CHCSCNC1),(Ever told) (you had) melanoma or any other types of cancer? (CHCOCNC1),Ever told you had C.O.P.D. emphysema or chronic bronchitis? (CHCCOPD3),(Ever told) you had a depressive disorder (ADDEPEV3),Ever told you have kidney disease? (CHCKDNY2),Told Had Arthritis (HAVARTH4),(Ever told) you had diabetes (DIABETE4),Marital Status (MARITAL),Education Level (EDUCA),Own or Rent Home (RENTHOM1),Are You A Veteran (VETERAN3),Employment Status (EMPLOY1),Income Level (INCOME3),Difficulty Concentrating or Remembering (DECIDE),Difficulty Walking or Climbing Stairs (DIFFWALK),Difficulty Dressing or Bathing (DIFFDRES),Difficulty Doing Errands Alone (DIFFALON),Smoked at Least 100 Cigarettes (SMOKE100),Frequency of Days Now Smoking (SMOKDAY2),Use of Smokeless Tobacco Products (USENOW3),"Do you now use e-cigarettes, or vaping products every day, some days, or not at all? (ECIGNOW3)",How old when you first started smoking? (LCSFIRST),"On average, how many cigarettes do you smoke each day? (LCSNUMCG)",Satisfaction with life (LSATISFY),How often get emotional support needed (EMTSUPRT),How often do you feel lonely? (SDLONELY),Were you not able to pay your bills? (SDHBILLS),Were you not able to pay utility bills or threatened to lose service? (SDHUTILS),"Has a lack of reliable transportation kept you from appointments, meetings, work, or getting things needed (SDHTRNSP)",Neighborhood Safe From Crime (HOWSAFE1),Sample Design Stratification Variable (_STSTR),Final weight: Land-line and cell-phone data (_LLCPWT),Computed Physical Health Status (_PHYS14D),Computed Mental Health Status (_MENT14D),Computed Race-Ethnicity grouping (_RACE),Imputed Age value collapsed above 80 (_AGE80),Computed Height in Meters (HTM4),Computed Weight in Kilograms (WTKG3),Computed body mass index (_BMI5),Computed body mass index categories (_BMI5CAT),Overweight or obese calculated variable (_RFBMI5),Computed number of children in household (_CHLDCNT),Number of packs of cigarettes smoked per day (_PACKDAY),Years smoked reported packs per day (_PACKYRS),Number of years since quit smoking cigarettes (_LCSYQTS),LCS Smoking Group (_LCSSMKG),Drink any alcoholic beverages in past 30 days (DRNKANY6),Computed drink-occasions-per-day (DROCDY4_),Binge Drinking Calculated Variable (_RFBING6),Computed number of drinks of alcohol beverages per week (_DRNKWK3),Heavy Alcohol Consumption Calculated Variable (_RFDRHV9),Flu Shot Calculated Variable (_FLSHOT7),Pneumonia Vaccination Calculated Variable (_PNEUMO3)
0,Alabama,2024000001,2024000001,Female,Good,2,NaN,NaN,Medicare,More than one,No,Within past year (anytime less than 12 months ago),Yes,Within the past year (anytime < 12 months ago),1 to 5,No,No,No,No - Go to Section 06.06 CHCSCNC1,NaN,Yes,No,No,No,No,Yes,No - Go to Section 07.01 AGE,Widowed,Grade 12 or GED (High school graduate),Own,No,Retired,Refused,No,No,No,No,No - Go to Section 11.03 USENOW3,NaN,Not at all,Never used e-cigarettes in your entire life,NaN,NaN,Very satisfied,Always,Never,No,No,No,Extremely safe,11011,261.525511,1-13 days when physical health not good,Zero days when mental health not good,"White only, non-Hispanic",78,163.0,5942.0,2249.0,Normal Weight,No,No children in household,NaN,NaN,NaN,Never smoker,No,5.40E-79,No,5.40E-79,No,Yes,No
1,Alabama,2024000002,2024000002,Male,Excellent,NaN,NaN,NaN,Medicare,"Yes, only one",No,Within past year (anytime less than 12 months ago),Yes,Within the past year (anytime < 12 months ago),1 to 5,No,Yes,No,No - Go to Section 06.06 CHCSCNC1,NaN,No,No,No,No,No,Yes,No - Go to Section 07.01 AGE,Married,College 4 years or more (College graduate),Own,Yes,Retired,"$200,000 or more",No,No,No,No,Yes,Not at all,Not at all,Never used e-cigarettes in your entire life,25,20,Very satisfied,Always,Never,No,No,No,Extremely safe,11011,307.169688,Zero days when physical health not good,Zero days when mental health not good,"White only, non-Hispanic",80,178.0,8165.0,2583.0,Overweight,Yes,No children in household,100.0,2.0,53.0,"Former smoker, < 20 Pack Years",No,5.40E-79,No,5.40E-79,No,Yes,Yes
2,Alabama,2024000003,2024000003,Male,Very good,30,NaN,1,A plan purchased through an employer or union (including plans purchased through another person's employer),No,Yes,5 or more years ago,Yes,5 or more years ago,"6 or more, but not all",No,No,No,No - Go to Section 06.06 CHCSCNC1,NaN,No,No,No,No,No,Yes,No - Go to Section 07.01 AGE,A member of an unmarried couple,College 1 year to 3 years (Some college or technical school),Own,Yes,Employed for wages,Refused,No,No,No,No,Yes,Every day,Not at all,Never used e-cigarettes in your entire life,14,15,Very satisfied,Usually,Never,No,No,No,Extremely safe,11011,2939.862806,14+ days when physical health not good,Zero days when mental health not good,"White only, non-Hispanic",59,198.0,8845.0,2253.0,Normal Weight,No,No children in household,75.0,34.0,NaN,"Current smoker, 20+ Pack Years",Yes,100,Yes,1400,No,NaN,NaN
3,Alabama,2024000004,2024000004,Male,Excellent,NaN,NaN,NaN,Medicare,"Yes, only one",No,Within past year (anytime less than 12 months ago),Yes,Within the past year (anytime < 12 months ago),NaN,No,No,No,No - Go to Section 06.06 CHCSCNC1,NaN,Yes,No,No,No,No,Yes,No - Go to Section 07.01 AGE,Married,College 4 years or more (College graduate),Own,No,Retired,"Less than $50,000 ($35,000 to < $50,000)",No,No,No,No,No - Go to Section 11.03 USENOW3,NaN,Not at all,Never used e-cigarettes in your entire life,NaN,NaN,Very satisfied,Always,Never,No,No,No,Safe,11011,153.584844,Zero days when physical health not good,Zero days when mental health not good,"White only, non-Hispanic",80,173.0,7484.0,2509.0,Overweight,Yes,No children in household,NaN,NaN,NaN,Never smoker,No,5.40E-79,No,5.40E-79,No,Yes,Yes
4,Alabama,2024000005,2024000005,Male,Good,NaN,NaN,NaN,Medicaid,"Yes, only one",No,Within past year (anytime less than 12 months ago),No,Within the past year (anytime < 12 months ago),1 to 5,No,No,No,No - Go to Section 06.06 CHCSCNC1,NaN,No,No,No,No,No,No,No - Go to Section 07.01 AGE,Never married,College 1 year to 3 years (Some college or technical school),Own,No,Unable to work,"Less than $20,000 ($15,000 to < $20,000)",No,Yes,No,Yes,No - Go to Section 11.03 USENOW3,NaN,Not at all,Used them in the past but do not currently use them at all,NaN,NaN,Satisfied,Rarely,Always,No,No,Yes,Extremely safe,11011,1229.623036,Zero days when physical health not good,Zero days when mental health not good,"White only, non-Hispanic",47,173.0,5897.0,1977.0,Normal Weight,No,No children in household,NaN,NaN,NaN,Never smoker,No,5.40E-79,No,5.40E-79,No,NaN,NaN

In [32]:

import re
import pandas as pd

# Topics that may contribute to deeper chronic-disease analysis
keywords = [
    "blood pressure", "hypertension", "cholesterol",
    "heart attack", "coronary", "stroke", "kidney",
    "diabetes", "asthma", "copd", "lung",
    "smok", "tobacco", "e-cigarette", "alcohol",
    "exercise", "physical activity", "walking",
    "fruit", "vegetable", "nutrition", "sleep",
    "weight", "bmi", "health insurance", "medical cost",
    "checkup", "doctor", "health care", "healthcare",
    "mental health", "physical health", "depression",
    "disability", "pain", "general health",
    "income", "education", "employment", "food insecurity",
    "housing", "transportation", "social support",
    "flu shot", "pneumonia", "cancer screening"
]

# Search column labels, not the full dataset values
all_columns = pd.Index(df.columns.astype(str))
pattern = re.compile("|".join(re.escape(k) for k in keywords), re.IGNORECASE)

candidate_columns = [
    col for col in all_columns
    if pattern.search(col)
]

# Exclude columns already included in final_df
existing_columns = set(final_df.columns)
additional_candidates = [
    col for col in candidate_columns
    if col not in existing_columns
]

candidates_table = pd.DataFrame({
    "Column_Name": additional_candidates,
    "Variable_Code": [
        re.search(r"\(([^()]*)\)\s*$", col).group(1)
        if re.search(r"\(([^()]*)\)\s*$", col)
        else "Code not identified"
        for col in additional_candidates
    ]
})

print("Additional candidate columns found:", len(candidates_table))
display(candidates_table)

Additional candidate columns found: 58

                                          Column_Name Variable_Code
0          Do you live in college housing? (COLGHOUS)      COLGHOUS
1          Do you live in college housing? (CCLGHOUS)      CCLGHOUS
2     Age When First Told You Had Diabetes (DIABAGE4)      DIABAGE4
3                 Reported Weight in Pounds (WEIGHT2)       WEIGHT2
4   Have you ever had a cervical cancer screening ...      CERVSCRN
5   Time since last cervical cancer screening test...      CRVCLCNC
6   Have a PAP test and recent cervical cancer scr...      CRVCLPAP
7   Have an H.P.V. test and recent cervical cancer...      CRVCLHPV
8   Were any CT or CAT scans done to check for lun...      LCSSCNCR
9    Days in past 30 had alcoholic beverage (ALCDAY4)       ALCDAY4
10  Avg alcoholic drinks per day in past 30 (AVEDR...      AVEDRNK4
11        Adult flu shot/spray past 12 mos (FLUSHOT7)      FLUSHOT7
12  When did you receive your most recent seasonal...      FLSHTMY3
13  Where did you get your last flu shot/vaccine? ...      IMFVPLA5
14                     Pneumonia shot ever (PNEUVAC4)      PNEUVAC4
15  Ever been told by a doctor or other health pro...      PREDIAB2
16      What type of diabetes do you have? (DIABTYPE)      DIABTYPE
17  When was the last time you took a course or cl...      DIABEDU1
18  Dr. Suggest Use of Physical Activity or Exerci...      ARTHEXER
19  What Type of Doctor Provides Majority of Your ...      CSRVDOC1
20  Ever Receive Instructions From A Doctor For Fo...      CSRVRTRN
21  Did Health Insurance Pay For All Of Your Cance...      CSRVINSR
22  Currently Have Physical Pain From Cancer Or Tr...      CSRVPAIN
23                  Is Pain Under Control? (CSRVCTL2)      CSRVCTL2
24  Have you discussed your difficulties with thin...      CDDISCU1
25  What Is The Main Health Problem, Illness, Disa...      CRGVPRB4
26  Live With a Problem Drinker/Alcoholic? (ACEDRINK)      ACEDRINK
27  Have you lost employment or had hours reduced?...      SDHEMPLY
28    Did you smoke marijuana or cannabis? (MARJSMOK)      MARJSMOK
29              Interval Since Last Smoked (LASTSMK2)      LASTSMK2
30       Stopped Smoking in past 12 months (STOPSMK2)      STOPSMK2
31  Do you usually smoke menthol cigarettes? (MENT...      MENTCIGS
32  Do you usually use menthol e-cigarettes? (MENT...      MENTECIG
33  Have you heard of heated tobacco products? (HE...      HEATTBCO
34     Hlth pro ever said child has asthma (CASTHDX2)      CASTHDX2
35                Child still have asthma? (CASTHNO2)      CASTHNO2
36                            Stratum weight (_STRWT)        _STRWT
37     Raw weighting factor used in raking (_RAWRAKE)      _RAWRAKE
38             Design weight use in raking (_WT2RAKE)      _WT2RAKE
39  Final child weight: Land-line and Cell-Phone d...      _CLLCPWT
40  Truncated design weight used in adult combined...      _LLCPWT2
41               Have any health insurance (_HLTHPL2)      _HLTHPL2
42  Respondents aged 18-64 with health insurance (...      _HCVU654
43  Leisure Time Physical Activity Calculated Vari...      _TOTINDA
44     Lifetime Asthma Calculated Variable (_LTASTH1)      _LTASTH1
45      Current Asthma Calculated Variable (_CASTHM1)      _CASTHM1
46                  Computed Asthma Status (_ASTHMS1)      _ASTHMS1
47  Computed level of education completed categori...       _EDUCAG
48              Computed income categories (_INCOMG1)      _INCOMG1
49                 Computed Smoking Status (_SMOKER3)      _SMOKER3
50     Current Smoking Calculated Variable (_RFSMOK3)      _RFSMOK3
51  Current E-cigarette User Calculated Variable (...      _CURECI3
52           How old when you last smoked? (LCSLAST_)      LCSLAST_
53  On average, how many cigarettes do you smoke e...      LCSNUMC_
54         Lung Cancer Screening Age Groups (_LCSAGE)       _LCSAGE
55       Number of years smoked cigarettes (_LCSYSMK)      _LCSYSMK
56       Had Chest CT Scan for Lung Cancer (_LCSCTSN)      _LCSCTSN
57  Meet USPSTF Lung Cancer Screening Guidelines (...      _LCSPSTF

In [33]:

import re
import pandas as pd

additional_codes = [
    "DIABAGE4", "DIABTYPE", "PREDIAB2", "DIABEDU1",
    "LCSSCNCR", "LCSLAST_", "LCSNUMC_", "_LCSAGE",
    "_LCSYSMK", "_LCSCTSN", "_LCSPSTF",
    "ALCDAY4", "AVEDRNK4",
    "FLUSHOT7", "FLSHTMY3", "IMFVPLA5", "PNEUVAC4",
    "_HLTHPL2", "_HCVU654", "_TOTINDA",
    "_LTASTH1", "_CASTHM1", "_ASTHMS1",
    "_EDUCAG", "_INCOMG1",
    "_SMOKER3", "_RFSMOK3", "_CURECI3",
    "WEIGHT2"
]


matched_columns = {}
for code in additional_codes:
    matches = [
        col for col in df.columns
        if str(col).strip().endswith(f"({code})")
        or str(col).strip() == code
    ]
    if matches:
        matched_columns[code] = matches[0]

missing_codes = [
    code for code in additional_codes
    if code not in matched_columns
]

# Add only columns that are not already in final_df
columns_to_add = [
    col for col in matched_columns.values()
    if col not in final_df.columns
]

final_df = pd.concat(
    [final_df, df[columns_to_add].copy()],
    axis=1
)

print("New columns added:", len(columns_to_add))
print("Total dataset shape:", final_df.shape)
print("Codes not found:", missing_codes)

display(final_df.head(5))

New columns added: 29
Total dataset shape: (457670, 102)
Codes not found: []

,State FIPS Code (_STATE),Annual Sequence Number (SEQNO),Primary Sampling Unit (_PSU),Sex of Respondent (SEXVAR),General Health (GENHLTH),Number of Days Physical Health Not Good (PHYSHLTH),Number of Days Mental Health Not Good (MENTHLTH),Poor Physical or Mental Health (POORHLTH),What is Your Current Primary Source of Health Care Coverage? (PRIMINS2),Have Personal Health Care Provider? (PERSDOC3),...,Leisure Time Physical Activity Calculated Variable (_TOTINDA),Lifetime Asthma Calculated Variable (_LTASTH1),Current Asthma Calculated Variable (_CASTHM1),Computed Asthma Status (_ASTHMS1),Computed level of education completed categories (_EDUCAG),Computed income categories (_INCOMG1),Computed Smoking Status (_SMOKER3),Current Smoking Calculated Variable (_RFSMOK3),Current E-cigarette User Calculated Variable (_CURECI3),Reported Weight in Pounds (WEIGHT2)
0,Alabama,2024000001,2024000001,Female,Good,2,NaN,NaN,Medicare,More than one,...,Had physical activity or exercise,No,No,Never,Graduated High School,Don't know/Not sure/Missing,Never smoked,No,Not currently using E-cigarettes,131
1,Alabama,2024000002,2024000002,Male,Excellent,NaN,NaN,NaN,Medicare,"Yes, only one",...,Had physical activity or exercise,No,No,Never,Graduated from College or Technical School,"$200,000 or more",Former smoker,No,Not currently using E-cigarettes,180
2,Alabama,2024000003,2024000003,Male,Very good,30,NaN,1,A plan purchased through an employer or union ...,No,...,Had physical activity or exercise,No,No,Never,Attended College or Technical School,Don't know/Not sure/Missing,Current smoker - now smokes every day,Yes,Not currently using E-cigarettes,195
3,Alabama,2024000004,2024000004,Male,Excellent,NaN,NaN,NaN,Medicare,"Yes, only one",...,Had physical activity or exercise,No,No,Never,Graduated from College or Technical School,"$35,000 to < $50,000",Never smoked,No,Not currently using E-cigarettes,165
4,Alabama,2024000005,2024000005,Male,Good,NaN,NaN,NaN,Medicaid,"Yes, only one",...,No physical activity or exercise in last 30 days,No,No,Never,Attended College or Technical School,"$15,000 to < $25,000",Never smoked,No,Not currently using E-cigarettes,130

In [34]:

print("Rows:", final_df.shape[0])
print("Columns:", final_df.shape[1])

display(pd.DataFrame({
    "Column_Name": final_df.columns,
    "Data_Type": final_df.dtypes.astype(str).values,
    "Missing_Percent": (
        final_df.isna().mean().values * 100
    ).round(2)
}))

final_df.to_csv(
    "BRFSS_2024_Expanded_Analysis.csv",
    index=False
)

Rows: 457670
Columns: 102

,Column_Name,Data_Type,Missing_Percent
0,State FIPS Code (_STATE),str,0.00
1,Annual Sequence Number (SEQNO),int64,0.00
2,Primary Sampling Unit (_PSU),int64,0.00
3,Sex of Respondent (SEXVAR),str,0.00
4,General Health (GENHLTH),str,0.00
...,...,...,...
97,Computed income categories (_INCOMG1),str,0.00
98,Computed Smoking Status (_SMOKER3),str,0.00
99,Current Smoking Calculated Variable (_RFSMOK3),str,0.00
100,Current E-cigarette User Calculated Variable (...,str,0.00
101,Reported Weight in Pounds (WEIGHT2),str,2.69

In [35]:
import pandas as pd

# Display all columns without truncation
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)

# Show the first 5 rows with all columns
display(final_df.head(5))

# Display dataset dimensions
print("Dataset shape:", final_df.shape)
print("Total rows:", final_df.shape[0])
print("Total columns:", final_df.shape[1])

,State FIPS Code (_STATE),Annual Sequence Number (SEQNO),Primary Sampling Unit (_PSU),Sex of Respondent (SEXVAR),General Health (GENHLTH),Number of Days Physical Health Not Good (PHYSHLTH),Number of Days Mental Health Not Good (MENTHLTH),Poor Physical or Mental Health (POORHLTH),What is Your Current Primary Source of Health Care Coverage? (PRIMINS2),Have Personal Health Care Provider? (PERSDOC3),Could Not Afford To See Doctor (MEDCOST1),Length of time since last routine checkup (CHECKUP1),Exercise in Past 30 Days (EXERANY2),Last Visited Dentist or Dental Clinic (LASTDEN4),Number of Permanent Teeth Removed (RMVTETH4),Ever Diagnosed with Heart Attack (CVDINFR4),Ever Diagnosed with Angina or Coronary Heart Disease (CVDCRHD4),Ever Diagnosed with a Stroke (CVDSTRK3),Ever Told Had Asthma (ASTHMA3),Still Have Asthma (ASTHNOW),(Ever told) (you had) skin cancer that is not melanoma? (CHCSCNC1),(Ever told) (you had) melanoma or any other types of cancer? (CHCOCNC1),Ever told you had C.O.P.D. emphysema or chronic bronchitis? (CHCCOPD3),(Ever told) you had a depressive disorder (ADDEPEV3),Ever told you have kidney disease? (CHCKDNY2),Told Had Arthritis (HAVARTH4),(Ever told) you had diabetes (DIABETE4),Marital Status (MARITAL),Education Level (EDUCA),Own or Rent Home (RENTHOM1),Are You A Veteran (VETERAN3),Employment Status (EMPLOY1),Income Level (INCOME3),Difficulty Concentrating or Remembering (DECIDE),Difficulty Walking or Climbing Stairs (DIFFWALK),Difficulty Dressing or Bathing (DIFFDRES),Difficulty Doing Errands Alone (DIFFALON),Smoked at Least 100 Cigarettes (SMOKE100),Frequency of Days Now Smoking (SMOKDAY2),Use of Smokeless Tobacco Products (USENOW3),"Do you now use e-cigarettes, or vaping products every day, some days, or not at all? (ECIGNOW3)",How old when you first started smoking? (LCSFIRST),"On average, how many cigarettes do you smoke each day? (LCSNUMCG)",Satisfaction with life (LSATISFY),How often get emotional support needed (EMTSUPRT),How often do you feel lonely? (SDLONELY),Were you not able to pay your bills? (SDHBILLS),Were you not able to pay utility bills or threatened to lose service? (SDHUTILS),"Has a lack of reliable transportation kept you from appointments, meetings, work, or getting things needed (SDHTRNSP)",Neighborhood Safe From Crime (HOWSAFE1),Sample Design Stratification Variable (_STSTR),Final weight: Land-line and cell-phone data (_LLCPWT),Computed Physical Health Status (_PHYS14D),Computed Mental Health Status (_MENT14D),Computed Race-Ethnicity grouping (_RACE),Imputed Age value collapsed above 80 (_AGE80),Computed Height in Meters (HTM4),Computed Weight in Kilograms (WTKG3),Computed body mass index (_BMI5),Computed body mass index categories (_BMI5CAT),Overweight or obese calculated variable (_RFBMI5),Computed number of children in household (_CHLDCNT),Number of packs of cigarettes smoked per day (_PACKDAY),Years smoked reported packs per day (_PACKYRS),Number of years since quit smoking cigarettes (_LCSYQTS),LCS Smoking Group (_LCSSMKG),Drink any alcoholic beverages in past 30 days (DRNKANY6),Computed drink-occasions-per-day (DROCDY4_),Binge Drinking Calculated Variable (_RFBING6),Computed number of drinks of alcohol beverages per week (_DRNKWK3),Heavy Alcohol Consumption Calculated Variable (_RFDRHV9),Flu Shot Calculated Variable (_FLSHOT7),Pneumonia Vaccination Calculated Variable (_PNEUMO3),Age When First Told You Had Diabetes (DIABAGE4),What type of diabetes do you have? (DIABTYPE),Ever been told by a doctor or other health professional that you have pre-diabetes or borderline diabetes? (PREDIAB2),When was the last time you took a course or class in how to manage your diabetes? (DIABEDU1),Were any CT or CAT scans done to check for lung cancer? (LCSSCNCR),How old when you last smoked? (LCSLAST_),"On average, how many cigarettes do you smoke each day? (LCSNUMC_)",Lung Cancer Screening Age Groups (_LCSAGE),Number of years smoked cigarettes (_LCSYSMK),Had Chest CT Scan for Lung Cancer (_LCSCTSN),Meet USPSTF Lung Cancer Screening Guidelines (_LCSPSTF),Days in past 30 had alcoholic beverage (ALCDAY4),Avg alcoholic drinks per day in past 30 (AVEDRNK4),Adult flu shot/spray past 12 mos (FLUSHOT7),When did you receive your most recent seasonal flu shot/spray? (FLSHTMY3),Where did you get your last flu shot/vaccine? (IMFVPLA5),Pneumonia shot ever (PNEUVAC4),Have any health insurance (_HLTHPL2),Respondents aged 18-64 with health insurance (_HCVU654),Leisure Time Physical Activity Calculated Variable (_TOTINDA),Lifetime Asthma Calculated Variable (_LTASTH1),Current Asthma Calculated Variable (_CASTHM1),Computed Asthma Status (_ASTHMS1),Computed level of education completed categories (_EDUCAG),Computed income categories (_INCOMG1),Computed Smoking Status (_SMOKER3),Current Smoking Calculated Variable (_RFSMOK3),Current E-cigarette User Calculated Variable (_CURECI3),Reported Weight in Pounds (WEIGHT2)
0,Alabama,2024000001,2024000001,Female,Good,2,NaN,NaN,Medicare,More than one,No,Within past year (anytime less than 12 months ago),Yes,Within the past year (anytime < 12 months ago),1 to 5,No,No,No,No - Go to Section 06.06 CHCSCNC1,NaN,Yes,No,No,No,No,Yes,No - Go to Section 07.01 AGE,Widowed,Grade 12 or GED (High school graduate),Own,No,Retired,Refused,No,No,No,No,No - Go to Section 11.03 USENOW3,NaN,Not at all,Never used e-cigarettes in your entire life,NaN,NaN,Very satisfied,Always,Never,No,No,No,Extremely safe,11011,261.525511,1-13 days when physical health not good,Zero days when mental health not good,"White only, non-Hispanic",78,163.0,5942.0,2249.0,Normal Weight,No,No children in household,NaN,NaN,NaN,Never smoker,No,5.40E-79,No,5.40E-79,No,Yes,No,NaN,NaN,NaN,NaN,Don't know/Not sure - Go to next section,NaN,NaN,Imputed Age 50 to 80,NaN,NaN,"Not Eligible, Don't know/Not sure, Refused, or Missing",No drinks in past 30 days - Go to Section 14.01 FLUSHOT7,NaN,Yes,Don't know/Not Sure,A doctor's office or health maintenance organization (HMO),No,Have some form of insurance,"Don't know/Not Sure, Refused or Missing",Had physical activity or exercise,No,No,Never,Graduated High School,Don't know/Not sure/Missing,Never smoked,No,Not currently using E-cigarettes,131
1,Alabama,2024000002,2024000002,Male,Excellent,NaN,NaN,NaN,Medicare,"Yes, only one",No,Within past year (anytime less than 12 months ago),Yes,Within the past year (anytime < 12 months ago),1 to 5,No,Yes,No,No - Go to Section 06.06 CHCSCNC1,NaN,No,No,No,No,No,Yes,No - Go to Section 07.01 AGE,Married,College 4 years or more (College graduate),Own,Yes,Retired,"$200,000 or more",No,No,No,No,Yes,Not at all,Not at all,Never used e-cigarettes in your entire life,25,20,Very satisfied,Always,Never,No,No,No,Extremely safe,11011,307.169688,Zero days when physical health not good,Zero days when mental health not good,"White only, non-Hispanic",80,178.0,8165.0,2583.0,Overweight,Yes,No children in household,100.0,2.0,53.0,"Former smoker, < 20 Pack Years",No,5.40E-79,No,5.40E-79,No,Yes,Yes,NaN,NaN,NaN,NaN,NaN,27,20.0,Imputed Age 50 to 80,2.0,Never had a Chest CT Scan,"Not Eligible, Don't know/Not sure, Refused, or Missing",No drinks in past 30 days - Go to Section 14.01 FLUSHOT7,NaN,Yes,92023,A doctor's office or health maintenance organization (HMO),Yes,Have some form of insurance,"Don't know/Not Sure, Refused or Missing",Had physical activity or exercise,No,No,Never,Graduated from College or Technical School,"$200,000 or more",Former smoker,No,Not currently using E-cigarettes,180
2,Alabama,2024000003,2024000003,Male,Very good,30,NaN,1,A plan purchased through an employer or union (including plans purchased through another person's employer),No,Yes,5 or more years ago,Yes,5 or more years ago,"6 or more, but not all",No,No,No,No - Go to Section 06.06 CHCSCNC1,NaN,No,No,No,No,No,Yes,No - Go to Section 07.01 AGE,A member of an unmarried couple,College 1 year to 3 years (Some college or technical school),Own,Yes,Employed for wages,Refused,No,No,No,No,Yes,Every day,Not at all,Never used e-cigarettes in your entire life,14,15,Very satisfied,Usually,Never,No,No,No,Extremely safe,11011,2939.862806,14+ days when physical health not good,Zero days when mental health not good,"White only, non-Hispanic",59,198.0,8845.0,2253.0,Normal Weight,No,No children in household,75.0,34.0,NaN,"Current smoker, 20+ Pack Years",Yes,100,Yes,1400,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,Imputed Age 50 to 80,45.0,Never had a Chest CT Scan,Do Not Meet USPSTF Guidelines,230,2,No - Go to Section 14.04 PNEUVAC4,NaN,NaN,No,Have some form of insurance,Have some form of health insurance,Had physical activity or exercise,No,No,Never,Attended College or Technical School,Don't know/Not sure/Missing,Current smoker - now smokes every day,Yes,Not currently using E-cigarettes,195
3,Alabama,2024000004,2024000004,Male,Excellent,NaN,NaN,NaN,Medicare,"Yes, only one",No,Within past year (anytime less than 12 months ago),Yes,Within the past year (anytime < 12 months ago),NaN,No,No,No,No - Go to Section 06.06 CHCSCNC1,NaN,Yes,No,No,No,No,Yes,No - Go to Section 07.01 AGE,Married,College 4 years or more (College graduate),Own,No,Retired,"Less than $50,000 ($35,000 to < $50,000)",No,No,No,No,No - Go to Section 11.03 USENOW3,NaN,Not at all,Never used e-cigarettes in your entire life,NaN,NaN,Very satisfied,Always,Never,No,No,No,Safe,11011,153.584844,Zero days when physical health not good,Zero days when mental health not good,"White only, non-Hispanic",80,173.0,7484.0,2509.0,Overweight,Yes,No children in household,NaN,NaN,NaN,Never smoker,No,5.40E-79,No,5.40E-79,No,Yes,Yes,NaN,NaN,NaN,NaN,Don't know/Not sure - Go to next section,NaN,NaN,Imputed Age 81 or older,NaN,NaN,"Not Eligible, Don't know/Not sure, Refused, or Missing",No drinks in past 30 days - Go to Section 14.01 FLUSHOT7,NaN,Yes,102023,"A store (supermarket, drug store)",Yes,Have some form of insurance,"Don't know/Not Sure, Refused or Missing",Had physical activity or exercise,No,No,Never,Graduated from College or Technical School,"$35,000 to < $50,000",Never smoked,No,Not currently using E-cigarettes,165
4,Alabama,2024000005,2024000005,Male,Good,NaN,NaN,NaN,Medicaid,"Yes, only one",No,Within past year (anytime less than 12 months ago),No,Within the past year (anytime < 12 months ago),1 to 5,No,No,No,No - Go to Section 06.06 CHCSCNC1,NaN,No,No,No,No,No,No,No - Go to Section 07.01 AGE,Never married,College 1 year to 3 years (Some college or technical school),Own,No,Unable to work,"Less than $20,000 ($15,000 to < $20,000)",No,Yes,No,Yes,No - Go to Section 11.03 USENOW3,NaN,Not at all,Used them in the past but do not currently use them at all,NaN,NaN,Satisfied,Rarely,Always,No,No,Yes,Extremely safe,11011,1229.623036,Zero days when physical health not good,Zero days when mental health not good,"White only, non-Hispanic",47,173.0,5897.0,1977.0,Normal Weight,No,No children in household,NaN,NaN,NaN,Never smoker,No,5.40E-79,No,5.40E-79,No,NaN,NaN,NaN,NaN,NaN,NaN,No - Go to next section,NaN,NaN,Imputed Age 18 to 49,NaN,Had Chest CT Scan for Other Reason,"Not Eligible, Don't know/Not sure, Refused, or Missing",No drinks in past 30 days - Go to Section 14.01 FLUSHOT7,NaN,Yes,92023,A doctor's office or health maintenance organization (HMO),Yes,Have some form of insurance,Have some form of health insurance,No physical activity or exercise in last 30 days,No,No,Never,Attended College or Technical School,"$15,000 to < $25,000",Never smoked,No,Not currently using E-cigarettes,130

Dataset shape: (457670, 102)
Total rows: 457670
Total columns: 102

In [36]:
from pathlib import Path

output_path = Path.cwd() / "BRFSS_2024_Expanded_Analysis.csv"

final_df.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

print("CSV file saved successfully!")
print("File location:", output_path.resolve())
print("File size (MB):", round(output_path.stat().st_size / (1024 * 1024), 2))

CSV file saved successfully!
File location: C:\Users\USER\OneDrive\Desktop\BRFSS\BRFSS_2024_Expanded_Analysis.csv
File size (MB): 535.47

In [37]:
import pandas as pd
import numpy as np
from pathlib import Path

# Use the expanded dataset
data = final_df.copy()

# Basic structure
print("=" * 70)
print("DATASET OVERVIEW")
print("=" * 70)
print(f"Rows: {data.shape[0]:,}")
print(f"Columns: {data.shape[1]:,}")
print(f"Memory usage: {data.memory_usage(deep=True).sum() / 1024**2:.2f} MB")

# Duplicate column names
print("\nDuplicate column names:")
print(data.columns[data.columns.duplicated()].tolist())

# Duplicate rows
print("\nExact duplicate rows:", data.duplicated().sum())

# Duplicate respondent IDs
id_candidates = [
    c for c in data.columns
    if "(SEQNO)" in c or c.strip() == "SEQNO"
]

for col in id_candidates:
    print(f"\nID column: {col}")
    print("Missing IDs:", data[col].isna().sum())
    print("Duplicate non-missing IDs:", data[col].dropna().duplicated().sum())

# Column information
column_report = pd.DataFrame({
    "Column": data.columns,
    "Data_Type": data.dtypes.astype(str).values,
    "Non_Missing": data.notna().sum().values,
    "Missing_Count": data.isna().sum().values,
    "Missing_Percent": (data.isna().mean().values * 100).round(2),
    "Unique_Values": data.nunique(dropna=True).values
})

display(column_report)

======================================================================
DATASET OVERVIEW
======================================================================
Rows: 457,670
Columns: 102
Memory usage: 819.43 MB

Duplicate column names:
[]

Exact duplicate rows: 0

ID column: Annual Sequence Number (SEQNO)
Missing IDs: 0
Duplicate non-missing IDs: 413757

,Column,Data_Type,Non_Missing,Missing_Count,Missing_Percent,Unique_Values
0,State FIPS Code (_STATE),str,457670,0,0.00,53
1,Annual Sequence Number (SEQNO),int64,457670,0,0.00,43913
2,Primary Sampling Unit (_PSU),int64,457670,0,0.00,43913
3,Sex of Respondent (SEXVAR),str,457670,0,0.00,2
4,General Health (GENHLTH),str,457665,5,0.00,7
...,...,...,...,...,...,...
97,Computed income categories (_INCOMG1),str,457670,0,0.00,8
98,Computed Smoking Status (_SMOKER3),str,457670,0,0.00,5
99,Current Smoking Calculated Variable (_RFSMOK3),str,457670,0,0.00,3
100,Current E-cigarette User Calculated Variable (_CURECI3),str,457670,0,0.00,3
101,Reported Weight in Pounds (WEIGHT2),str,445337,12333,2.69,631

In [38]:
disease_codes = [
    "DIABETE4",
    "CVDINFR4",
    "CVDCRHD4",
    "CVDSTRK3",
    "CHCKDNY2",
    "ADDEPEV3",
    "CHCCOPD3",
    "ASTHMA3",
    "ASTHNOW",
    "_LTASTH1",
    "_CASTHM1",
    "_ASTHMS1"
]

disease_columns = [
    c for c in data.columns
    if any(c.strip().endswith(f"({code})") for code in disease_codes)
    or c.strip() in disease_codes
]

print("Disease variables found:", len(disease_columns))
print(disease_columns)

for col in disease_columns:
    print(f"\n{'=' * 60}\n{col}")
    print("Missing:", data[col].isna().sum())
    print("Missing %:", round(data[col].isna().mean() * 100, 2))
    display(
        data[col]
        .value_counts(dropna=False)
        .head(20)
        .rename_axis("Response")
        .reset_index(name="Count")
    )

Disease variables found: 12
['Ever Diagnosed with Heart Attack (CVDINFR4)', 'Ever Diagnosed with Angina or Coronary Heart Disease (CVDCRHD4)', 'Ever Diagnosed with a Stroke (CVDSTRK3)', 'Ever Told Had Asthma (ASTHMA3)', 'Still Have Asthma (ASTHNOW)', 'Ever told you had C.O.P.D. emphysema or chronic bronchitis? (CHCCOPD3)', '(Ever told) you had a depressive disorder (ADDEPEV3)', 'Ever told you have kidney disease? (CHCKDNY2)', '(Ever told) you had diabetes (DIABETE4)', 'Lifetime Asthma Calculated Variable (_LTASTH1)', 'Current Asthma Calculated Variable (_CASTHM1)', 'Computed Asthma Status (_ASTHMS1)']

============================================================
Ever Diagnosed with Heart Attack (CVDINFR4)
Missing: 2
Missing %: 0.0

              Response   Count
0                   No  427883
1                  Yes   26672
2  Don't know/Not sure    2857
3              Refused     256
4                  NaN       2

============================================================
Ever Diagnosed with Angina or Coronary Heart Disease (CVDCRHD4)
Missing: 3
Missing %: 0.0

              Response   Count
0                   No  424581
1                  Yes   28511
2  Don't know/Not sure    4297
3              Refused     278
4                  NaN       3

============================================================
Ever Diagnosed with a Stroke (CVDSTRK3)
Missing: 3
Missing %: 0.0

              Response   Count
0                   No  435557
1                  Yes   20661
2  Don't know/Not sure    1244
3              Refused     205
4                  NaN       3

============================================================
Ever Told Had Asthma (ASTHMA3)
Missing: 3
Missing %: 0.0

                                             Response   Count
0                   No - Go to Section 06.06 CHCSCNC1  383772
1                                                 Yes   72037
2  Don't know/Not Sure - Go to Section 06.06 CHCSCNC1    1650
3              Refused - Go to Section 06.06 CHCSCNC1     208
4                                                 NaN       3

============================================================
Still Have Asthma (ASTHNOW)
Missing: 385633
Missing %: 84.26

              Response   Count
0                  NaN  385633
1                  Yes   49694
2                   No   20267
3  Don't know/Not Sure    2019
4              Refused      57

============================================================
Ever told you had C.O.P.D. emphysema or chronic bronchitis? (CHCCOPD3)
Missing: 7
Missing %: 0.0

                Response   Count
0                     No  418575
1                    Yes   36921
2  Don't know / Not sure    1921
3                Refused     246
4                    NaN       7

============================================================
(Ever told) you had a depressive disorder (ADDEPEV3)
Missing: 5
Missing %: 0.0

              Response   Count
0                   No  358881
1                  Yes   96125
2  Don't know/Not sure    2066
3              Refused     593
4                  NaN       5

============================================================
Ever told you have kidney disease? (CHCKDNY2)
Missing: 6
Missing %: 0.0

                Response   Count
0                     No  431939
1                    Yes   23752
2  Don't know / Not sure    1715
3                Refused     258
4                    NaN       6

============================================================
(Ever told) you had diabetes (DIABETE4)
Missing: 4
Missing %: 0.0

,Response,Count
0,No - Go to Section 07.01 AGE,376125
1,Yes,65809
2,"No, pre-diabetes or borderline diabetes - Go to Section 07.01 AGE",11307
3,"Yes, but female told only during pregnancy - Go to Section 07.01 AGE",3395
4,Don't know/Not Sure - Go to Section 07.01 AGE,798
5,Refused - Go to Section 07.01 AGE,232
6,NaN,4

============================================================
Lifetime Asthma Calculated Variable (_LTASTH1)
Missing: 0
Missing %: 0.0

                                 Response   Count
0                                      No  383772
1                                     Yes   72037
2  Don't know/Not Sure Or Refused/Missing    1861

============================================================
Current Asthma Calculated Variable (_CASTHM1)
Missing: 0
Missing %: 0.0

                                 Response   Count
0                                      No  404039
1                                     Yes   49694
2  Don't know/Not Sure Or Refused/Missing    3937

============================================================
Computed Asthma Status (_ASTHMS1)
Missing: 0
Missing %: 0.0

                                 Response   Count
0                                   Never  383772
1                                 Current   49694
2                                  Former   20267
3  Don't know/Not Sure Or Refused/Missing    3937

In [39]:
# Count skip-routing and special-response text
special_patterns = [
    "go to section",
    "don't know",
    "not sure",
    "refused",
    "missing",
    "not asked",
    "not applicable"
]

special_rows = []

for col in data.select_dtypes(include=["object", "string"]).columns:
    values = data[col].astype("string").str.lower()

    for pattern in special_patterns:
        count = values.str.contains(
            pattern, regex=False, na=False
        ).sum()

        if count > 0:
            special_rows.append({
                "Column": col,
                "Pattern": pattern,
                "Count": int(count),
                "Percent_of_all_rows": round(
                    count / len(data) * 100, 2
                )
            })

special_values_report = pd.DataFrame(special_rows)

if not special_values_report.empty:
    display(
        special_values_report.sort_values(
            ["Column", "Count"],
            ascending=[True, False]
        )
    )
else:
    print("No matching special-response text found.")

,Column,Pattern,Count,Percent_of_all_rows
52,(Ever told) (you had) melanoma or any other types of cancer? (CHCOCNC1),don't know,2098,0.46
53,(Ever told) (you had) melanoma or any other types of cancer? (CHCOCNC1),not sure,2098,0.46
54,(Ever told) (you had) melanoma or any other types of cancer? (CHCOCNC1),refused,343,0.07
49,(Ever told) (you had) skin cancer that is not melanoma? (CHCSCNC1),don't know,2761,0.60
50,(Ever told) (you had) skin cancer that is not melanoma? (CHCSCNC1),not sure,2761,0.60
...,...,...,...,...
187,When was the last time you took a course or class in how to manage your diabetes? (DIABEDU1),not sure,547,0.12
188,When was the last time you took a course or class in how to manage your diabetes? (DIABEDU1),refused,41,0.01
210,Where did you get your last flu shot/vaccine? (IMFVPLA5),don't know,967,0.21
211,Where did you get your last flu shot/vaccine? (IMFVPLA5),not sure,967,0.21
212,Where did you get your last flu shot/vaccine? (IMFVPLA5),refused,166,0.04

In [40]:
numeric_data = data.select_dtypes(include="number")

numeric_report = pd.DataFrame({
    "Column": numeric_data.columns,
    "Missing_Count": numeric_data.isna().sum().values,
    "Unique_Values": numeric_data.nunique().values,
    "Minimum": numeric_data.min().values,
    "Maximum": numeric_data.max().values,
    "Mean": numeric_data.mean().round(3).values,
    "Median": numeric_data.median().round(3).values
})

display(numeric_report)

,Column,Missing_Count,Unique_Values,Minimum,Maximum,Mean,Median
0,Annual Sequence Number (SEQNO),0,43913,2.024000e+09,2.024044e+09,2.024007e+09,2.024005e+09
1,Primary Sampling Unit (_PSU),0,43913,2.024000e+09,2.024044e+09,2.024007e+09,2.024005e+09
2,Sample Design Stratification Variable (_STSTR),0,2393,1.101100e+04,7.820220e+05,3.101415e+05,3.111810e+05
3,Final weight: Land-line and cell-phone data (_LLCPWT),0,256417,1.228580e-02,4.958219e+04,5.763620e+02,2.637400e+02
4,Imputed Age value collapsed above 80 (_AGE80),0,63,1.800000e+01,8.000000e+01,5.508500e+01,5.800000e+01
5,Computed Height in Meters (HTM4),24060,124,9.100000e+01,2.410000e+02,1.701660e+02,1.700000e+02
6,Computed Weight in Kilograms (WTKG3),36392,612,2.268000e+03,2.903000e+04,8.300485e+03,8.074000e+03
7,Computed body mass index (_BMI5),43037,4198,1.200000e+03,9.984000e+03,2.855680e+03,2.744000e+03
8,Number of packs of cigarettes smoked per day (_PACKDAY),304978,126,5.000000e+00,2.450000e+03,7.535900e+01,5.000000e+01
9,Years smoked reported packs per day (_PACKYRS),310400,273,5.400000e-79,1.274000e+03,2.022700e+01,1.300000e+01
10,Number of years since quit smoking cigarettes (_LCSYQTS),337067,108,-3.000000e+01,8.300000e+01,2.189400e+01,1.900000e+01
11,"On average, how many cigarettes do you smoke each day? (LCSNUMC_)",304978,126,1.000000e+00,4.900000e+02,1.507200e+01,1.000000e+01
12,Number of years smoked cigarettes (_LCSYSMK),305970,89,5.400000e-79,9.400000e+01,2.446000e+01,2.200000e+01

In [41]:
numeric_codes = [
    "HTM4", "WTKG3", "_BMI5", "WEIGHT2",
    "_LLCPWT", "_PACKDAY", "_PACKYRS",
    "_DRNKWK3", "DROCDY4_", "ALCDAY4",
    "AVEDRNK4", "LCSNUMCG", "LCSNUMC_"
]

for code in numeric_codes:
    matches = [
        c for c in data.columns
        if c.strip().endswith(f"({code})")
        or c.strip() == code
    ]

    for col in matches:
        print(f"\n{col}")
        print(data[col].describe(percentiles=[0.01, 0.25, 0.5, 0.75, 0.99]))
        print("Most frequent values:")
        print(data[col].value_counts(dropna=False).head(10))

Computed Height in Meters (HTM4)
count    433610.000000
mean        170.165995
std          10.822765
min          91.000000
1%          150.000000
25%         163.000000
50%         170.000000
75%         178.000000
99%         193.000000
max         241.000000
Name: Computed Height in Meters (HTM4), dtype: float64
Most frequent values:
Computed Height in Meters (HTM4)
168.0    37894
163.0    36300
170.0    34821
165.0    33649
178.0    33270
173.0    31992
175.0    30790
160.0    29720
183.0    29707
157.0    28003
Name: count, dtype: int64

Computed Weight in Kilograms (WTKG3)
count    421278.000000
mean       8300.484516
std        2141.833796
min        2268.000000
1%         4627.000000
25%        6804.000000
50%        8074.000000
75%        9525.000000
99%       14742.000000
max       29030.000000
Name: Computed Weight in Kilograms (WTKG3), dtype: float64
Most frequent values:
Computed Weight in Kilograms (WTKG3)
NaN       36392
9072.0    22131
8165.0    20305
6804.0    17972
7257.0    17747
7711.0    16674
8618.0    14759
6350.0    13214
7938.0    12062
9979.0    11375
Name: count, dtype: int64

Computed body mass index (_BMI5)
count    414633.000000
mean       2855.680093
std         658.616131
min        1200.000000
1%         1772.000000
25%        2414.000000
50%        2744.000000
75%        3175.000000
99%        4963.360000
max        9984.000000
Name: Computed body mass index (_BMI5), dtype: float64
Most frequent values:
Computed body mass index (_BMI5)
NaN       43037
2663.0     4428
2744.0     3378
2746.0     3364
2441.0     3300
2712.0     3167
2510.0     2768
3228.0     2476
2870.0     2389
2953.0     2387
Name: count, dtype: int64

Reported Weight in Pounds (WEIGHT2)
count     445337
unique       631
top          200
freq       22131
Name: Reported Weight in Pounds (WEIGHT2), dtype: object
Most frequent values:
Reported Weight in Pounds (WEIGHT2)
200        22131
180        20305
150        17972
160        17747
170        16674
Refused    16301
190        14759
140        13214
NaN        12333
175        12062
Name: count, dtype: int64

Final weight: Land-line and cell-phone data (_LLCPWT)
count    457670.000000
mean        576.361549
std        1171.591566
min           0.012286
1%           10.970441
25%         106.608408
50%         263.739622
75%         581.612255
99%        5294.301337
max       49582.191040
Name: Final weight: Land-line and cell-phone data (_LLCPWT), dtype: float64
Most frequent values:
Final weight: Land-line and cell-phone data (_LLCPWT)
247.048998    153
247.246655    131
178.692322    126
210.744499    120
141.282619    119
269.890823    108
173.143832    108
209.907810    102
182.582326    100
160.737714     98
Name: count, dtype: int64

Number of packs of cigarettes smoked per day (_PACKDAY)
count    152692.000000
mean         75.358663
std          62.281828
min           5.000000
1%            5.000000
25%          35.000000
50%          50.000000
75%         100.000000
99%         300.000000
max        2450.000000
Name: Number of packs of cigarettes smoked per day (_PACKDAY), dtype: float64
Most frequent values:
Number of packs of cigarettes smoked per day (_PACKDAY)
NaN      304978
100.0     43606
50.0      34040
25.0      11935
75.0       9149
200.0      6683
15.0       6296
150.0      5858
10.0       5769
20.0       5399
Name: count, dtype: int64

Years smoked reported packs per day (_PACKYRS)
count    1.472700e+05
mean     2.022677e+01
std      2.367835e+01
min      5.400000e-79
1%       5.400000e-79
25%      5.000000e+00
50%      1.300000e+01
75%      2.800000e+01
99%      1.020000e+02
max      1.274000e+03
Name: Years smoked reported packs per day (_PACKYRS), dtype: float64
Most frequent values:
Years smoked reported packs per day (_PACKYRS)
NaN             310400
1.000000e+00      9651
2.000000e+00      8061
3.000000e+00      6552
5.400000e-79      6307
5.000000e+00      5962
4.000000e+00      5713
6.000000e+00      5050
8.000000e+00      4678
7.000000e+00      4323
Name: count, dtype: int64

Computed number of drinks of alcohol beverages per week (_DRNKWK3)
count       457670
unique         283
top       5.40E-79
freq        203671
Name: Computed number of drinks of alcohol beverages per week (_DRNKWK3), dtype: object
Most frequent values:
Computed number of drinks of alcohol beverages per week (_DRNKWK3)
5.40E-79                               203671
Don't know/Not sure/Refused/Missing     46698
23                                      22651
47                                      19476
93                                      12669
200                                     10629
100                                     10059
700                                      9128
70                                       8672
400                                      8628
Name: count, dtype: int64

Computed drink-occasions-per-day (DROCDY4_)
count       457669
unique          36
top       5.40E-79
freq        203261
Name: Computed drink-occasions-per-day (DROCDY4_), dtype: object
Most frequent values:
Computed drink-occasions-per-day (DROCDY4_)
5.40E-79                                  203261
Don't know/Not Sure Or Refused/Missing     43777
3                                          34424
7                                          25375
14                                         19949
100                                        18969
29                                         15899
10                                         14523
43                                         11525
13                                         10978
Name: count, dtype: int64

Days in past 30 had alcoholic beverage (ALCDAY4)
count                                                       418449
unique                                                          41
top       No drinks in past 30 days - Go to Section 14.01 FLUSHOT7
freq                                                        203261
Name: Days in past 30 had alcoholic beverage (ALCDAY4), dtype: object
Most frequent values:
Days in past 30 had alcoholic beverage (ALCDAY4)
No drinks in past 30 days - Go to Section 14.01 FLUSHOT7    203261
NaN                                                          39221
201                                                          34424
202                                                          25375
101                                                          19949
102                                                          15899
203                                                          14523
230                                                          13056
103                                                          11426
204                                                          10978
Name: count, dtype: int64

Avg alcoholic drinks per day in past 30 (AVEDRNK4)
count     209741
unique        50
top            1
freq       89930
Name: Avg alcoholic drinks per day in past 30 (AVEDRNK4), dtype: object
Most frequent values:
Avg alcoholic drinks per day in past 30 (AVEDRNK4)
NaN                    247929
1                       89930
2                       64218
3                       25062
4                       11014
5                        6020
6                        4933
Don't know/Not sure      2015
10                       1446
8                        1437
Name: count, dtype: int64

On average, how many cigarettes do you smoke each day? (LCSNUMCG)
count     158047
unique       128
top           20
freq       43606
Name: On average, how many cigarettes do you smoke each day? (LCSNUMCG), dtype: object
Most frequent values:
On average, how many cigarettes do you smoke each day? (LCSNUMCG)
NaN    299623
20      43606
10      34040
5       11935
15       9149
40       6683
3        6296
30       5858
2        5769
4        5399
Name: count, dtype: int64

On average, how many cigarettes do you smoke each day? (LCSNUMC_)
count    152692.000000
mean         15.071733
std          12.456366
min           1.000000
1%            1.000000
25%           7.000000
50%          10.000000
75%          20.000000
99%          60.000000
max         490.000000
Name: On average, how many cigarettes do you smoke each day? (LCSNUMC_), dtype: float64
Most frequent values:
On average, how many cigarettes do you smoke each day? (LCSNUMC_)
NaN     304978
20.0     43606
10.0     34040
5.0      11935
15.0      9149
40.0      6683
3.0       6296
30.0      5858
2.0       5769
4.0       5399
Name: count, dtype: int64

In [42]:
def find_column(code):
    matches = [
        c for c in data.columns
        if c.strip().endswith(f"({code})")
        or c.strip() == code
    ]
    return matches[0] if matches else None


variable_pairs = [
    ("ASTHMA3", "_LTASTH1"),
    ("ASTHMA3", "_CASTHM1"),
    ("ASTHNOW", "_CASTHM1"),
    ("SMOKE100", "_SMOKER3"),
    ("EXERANY2", "_TOTINDA"),
    ("PRIMINS2", "_HLTHPL2"),
    ("EDUCA", "_EDUCAG"),
    ("INCOME3", "_INCOMG1")
]

for code_a, code_b in variable_pairs:
    col_a = find_column(code_a)
    col_b = find_column(code_b)

    if col_a and col_b:
        print(f"\n{'=' * 65}")
        print(f"{code_a} vs {code_b}")

        # Compare responses only where both are available
        paired = data[[col_a, col_b]].dropna()

        print("Comparable rows:", len(paired))
        print("Agreement rate:",
              round((paired[col_a] == paired[col_b]).mean() * 100, 2),
              "%")

        display(pd.crosstab(
            paired[col_a],
            paired[col_b],
            margins=True
        ))

=================================================================
ASTHMA3 vs _LTASTH1
Comparable rows: 457667
Agreement rate: 15.74 %

Lifetime Asthma Calculated Variable (_LTASTH1),Don't know/Not Sure Or Refused/Missing,No,Yes,All
Ever Told Had Asthma (ASTHMA3),,,,
Don't know/Not Sure - Go to Section 06.06 CHCSCNC1,1650,0,0,1650
No - Go to Section 06.06 CHCSCNC1,0,383771,1,383772
Refused - Go to Section 06.06 CHCSCNC1,208,0,0,208
Yes,0,1,72036,72037
All,1858,383772,72037,457667

=================================================================
ASTHMA3 vs _CASTHM1
Comparable rows: 457667
Agreement rate: 10.86 %

Current Asthma Calculated Variable (_CASTHM1),Don't know/Not Sure Or Refused/Missing,No,Yes,All
Ever Told Had Asthma (ASTHMA3),,,,
Don't know/Not Sure - Go to Section 06.06 CHCSCNC1,1650,0,0,1650
No - Go to Section 06.06 CHCSCNC1,0,383771,1,383772
Refused - Go to Section 06.06 CHCSCNC1,208,0,0,208
Yes,2076,20268,49693,72037
All,3934,404039,49694,457667

=================================================================
ASTHNOW vs _CASTHM1
Comparable rows: 72037
Agreement rate: 97.11 %

Current Asthma Calculated Variable (_CASTHM1),Don't know/Not Sure Or Refused/Missing,No,Yes,All
Still Have Asthma (ASTHNOW),,,,
Don't know/Not Sure,2019,0,0,2019
No,0,20266,1,20267
Refused,57,0,0,57
Yes,0,2,49692,49694
All,2076,20268,49693,72037

=================================================================
SMOKE100 vs _SMOKER3
Comparable rows: 428810
Agreement rate: 0.0 %

Computed Smoking Status (_SMOKER3),Current smoker - now smokes every day,Current smoker - now smokes some days,Don't know/Refused/Missing,Former smoker,Never smoked,All
Smoked at Least 100 Cigarettes (SMOKE100),,,,,,
Don't know/Not Sure - Go to Section 11.03 USENOW3,0,0,2062,0,0,2062
No - Go to Section 11.03 USENOW3,0,0,0,1,258955,258956
Refused - Go to Section 11.03 USENOW3,0,0,550,0,0,550
Yes,33118,13976,550,119597,1,167242
All,33118,13976,3162,119598,258956,428810

=================================================================
EXERANY2 vs _TOTINDA
Comparable rows: 457667
Agreement rate: 0.0 %

Leisure Time Physical Activity Calculated Variable (_TOTINDA),Don't know/Refused/Missing,Had physical activity or exercise,No physical activity or exercise in last 30 days,All
Exercise in Past 30 Days (EXERANY2),,,,
Don't know/Not Sure,860,0,0,860
No,0,1,106293,106294
Refused,452,0,0,452
Yes,0,350060,1,350061
All,1312,350061,106294,457667

=================================================================
PRIMINS2 vs _HLTHPL2
Comparable rows: 457667
Agreement rate: 0.0 %

Have any health insurance (_HLTHPL2),Do not have some form of health insurance,"Don't know, refused or missing insurance response",Have some form of insurance,All
What is Your Current Primary Source of Health Care Coverage? (PRIMINS2),,,,
A plan purchased through an employer or union (including plans purchased through another person's employer),1,0,155359,155360
A private nongovernmental plan that you or another family member buys on your own,0,0,38611,38611
Children's Health Insurance Program (CHIP),0,0,144,144
Don't know/Not Sure,0,12524,0,12524
Indian Health Service,0,0,1409,1409
Medicaid,0,0,32847,32847
Medicare,0,0,145567,145567
Medigap,0,0,386,386
Military related health care: TRICARE (CHAMPUS) / VA health care / CHAMP- VA,0,0,16939,16939
No coverage of any type,25405,0,1,25406
Other government program,0,0,10128,10128
Refused,0,6017,0,6017
State sponsored health plan,0,0,12329,12329
All,25406,18541,413720,457667

=================================================================
EDUCA vs _EDUCAG
Comparable rows: 457663
Agreement rate: 0.0 %

Computed level of education completed categories (_EDUCAG),Attended College or Technical School,Did not graduate High School,Don't know/Not sure/Missing,Graduated High School,Graduated from College or Technical School,All
Education Level (EDUCA),,,,,,
College 1 year to 3 years (Some college or technical school),120730,0,0,0,2,120732
College 4 years or more (College graduate),2,1,0,1,191545,191549
Grade 12 or GED (High school graduate),0,0,0,115876,1,115877
Grades 1 through 8 (Elementary),0,9226,0,0,0,9226
Grades 9 through 11 (Some high school),0,17199,0,0,1,17200
Never attended school or only kindergarten,0,723,0,0,0,723
Refused,0,0,2356,0,0,2356
All,120732,27149,2356,115877,191549,457663

=================================================================
INCOME3 vs _INCOMG1
Comparable rows: 448401
Agreement rate: 6.62 %

Computed income categories (_INCOMG1),"$100,000 to < $200,000","$15,000 to < $25,000","$200,000 or more","$25,000 to < $35,000","$35,000 to < $50,000","$50,000 to < $100,000",Don't know/Not sure/Missing,"Less than $15,000",All
Income Level (INCOME3),,,,,,,,,
"$200,000 or more",1,1,29691,0,1,0,0,0,29694
Don't know/Not sure,0,0,0,0,0,0,37112,1,37113
"Less than $10,000",0,0,0,0,0,0,0,10258,10258
"Less than $100,000 ($75,000 to < $100,000)",0,0,0,1,0,51699,0,0,51700
"Less than $15,000 ($10,000 to < $15,000)",0,0,0,0,0,0,1,10541,10542
"Less than $150,000 ($100,000 to < $150,000)",55777,0,1,0,0,0,0,0,55778
"Less than $20,000 ($15,000 to < $20,000)",0,13662,0,0,0,0,0,0,13662
"Less than $200,000 ($150,000 to < $200,000)",26675,0,0,0,0,0,0,0,26675
"Less than $25,000 ($20,000 to < $25,000)",0,19840,1,0,0,0,0,0,19841
"Less than $35,000 ($25,000 to < $35,000)",0,0,0,41701,0,1,0,0,41702
"Less than $50,000 ($35,000 to < $50,000)",0,0,1,0,49684,1,0,0,49686
"Less than $75,000 ($50,000 to < $75,000)",0,0,0,0,1,60708,0,0,60709
Refused,0,0,0,0,0,0,41041,0,41041
All,82453,33503,29694,41702,49686,112409,78154,20800,448401

In [44]:
output_dir = Path.cwd() / "BRFSS_Validation_Reports"
output_dir.mkdir(parents=True, exist_ok=True)

column_report.to_csv(
    output_dir / "column_quality_report.csv",
    index=False,
    encoding="utf-8-sig"
)

numeric_report.to_csv(
    output_dir / "numeric_summary_report.csv",
    index=False,
    encoding="utf-8-sig"
)

special_values_report.to_csv(
    output_dir / "special_response_report.csv",
    index=False,
    encoding="utf-8-sig"
)

# Save the current data unchanged as a checkpoint
data.to_csv(
    output_dir / "BRFSS_2024_PreCleaning_Checkpoint.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Validation reports saved to:")
print(output_dir.resolve())

Validation reports saved to:
C:\Users\USER\OneDrive\Desktop\BRFSS\BRFSS_Validation_Reports

In [45]:

from pathlib import Path
import pandas as pd

# 1. Variables expected from the previously documented 102-column dataset
expected_variables = [
    "_STATE", "SEQNO", "_PSU", "SEXVAR", "GENHLTH",
    "PHYSHLTH", "MENTHLTH", "POORHLTH", "PRIMINS2", "PERSDOC3",
    "MEDCOST1", "CHECKUP1", "EXERANY2", "LASTDEN4", "RMVTETH4",
    "CVDINFR4", "CVDCRHD4", "CVDSTRK3", "ASTHMA3", "ASTHNOW",
    "CHCSCNC1", "CHCOCNC1", "CHCCOPD3", "ADDEPEV3", "CHCKDNY2",
    "HAVARTH4", "DIABETE4", "MARITAL", "EDUCA", "RENTHOM1",
    "VETERAN3", "EMPLOY1", "INCOME3", "DECIDE", "DIFFWALK",
    "DIFFDRES", "DIFFALON", "SMOKE100", "SMOKDAY2", "USENOW3",
    "ECIGNOW3", "LCSFIRST", "LCSNUMCG", "LSATISFY", "EMTSUPRT",
    "SDLONELY", "SDHBILLS", "SDHUTILS", "SDHTRNSP", "HOWSAFE1",
    "_STSTR", "_LLCPWT", "_PHYS14D", "_MENT14D", "_RACE",
    "_AGE80", "HTM4", "WTKG3", "_BMI5", "_BMI5CAT",
    "_RFBMI5", "_CHLDCNT", "_PACKDAY", "_PACKYRS", "_LCSYQTS",
    "_LCSSMKG", "DRNKANY6", "DROCDY4_", "_RFBING6", "_DRNKWK3",
    "_RFDRHV9", "_FLSHOT7", "_PNEUMO3", "DIABAGE4", "DIABTYPE",
    "PREDIAB2", "DIABEDU1", "LCSSCNCR", "LCSLAST_", "LCSNUMC_",
    "_LCSAGE", "_LCSYSMK", "_LCSCTSN", "_LCSPSTF", "ALCDAY4",
    "AVEDRNK4", "FLUSHOT7", "FLSHTMY3", "IMFVPLA5", "PNEUVAC4",
    "_HLTHPL2", "_HCVU654", "_TOTINDA", "_LTASTH1", "_CASTHM1",
    "_ASTHMS1", "_EDUCAG", "_INCOMG1", "_SMOKER3", "_RFSMOK3",
    "_CURECI3", "WEIGHT2"
]

# 2. Compare the expected variables with the actual dataset columns
actual_columns = list(data.columns)

missing_variables = [
    col for col in expected_variables
    if col not in actual_columns
]

unexpected_columns = [
    col for col in actual_columns
    if col not in expected_variables
]

# 3. Build a detailed variable-presence report
variable_presence_report = pd.DataFrame({
    "Variable": expected_variables,
    "Present_in_Data": [
        col in actual_columns for col in expected_variables
    ],
    "Data_Type": [
        str(data[col].dtype) if col in actual_columns else None
        for col in expected_variables
    ],
    "Missing_Values": [
        int(data[col].isna().sum()) if col in actual_columns else None
        for col in expected_variables
    ],
    "Non_Missing_Values": [
        int(data[col].notna().sum()) if col in actual_columns else None
        for col in expected_variables
    ],
    "Unique_Values": [
        int(data[col].nunique(dropna=True))
        if col in actual_columns else None
        for col in expected_variables
    ]
})

# 4. Save the verification report
output_dir = Path.cwd() / "BRFSS_Validation_Reports"
output_dir.mkdir(parents=True, exist_ok=True)

variable_presence_report.to_csv(
    output_dir / "variable_presence_verification.csv",
    index=False,
    encoding="utf-8-sig"
)

# 5. Print the verification results
print("=" * 60)
print("BRFSS VARIABLE PRESENCE VERIFICATION")
print("=" * 60)

print(f"Dataset shape: {data.shape}")
print(f"Expected variables: {len(expected_variables)}")
print(f"Unique expected variable names: {len(set(expected_variables))}")
print(f"Expected variables found: {len(expected_variables) - len(missing_variables)}")
print(f"Expected variables missing: {len(missing_variables)}")
print(f"Actual columns not in expected list: {len(unexpected_columns)}")

if missing_variables:
    print("\nMissing variables:")
    for col in missing_variables:
        print(f"- {col}")
else:
    print("\nAll expected variables are present.")

if unexpected_columns:
    print("\nColumns outside the expected list:")
    for col in unexpected_columns:
        print(f"- {col}")

duplicate_column_names = data.columns[data.columns.duplicated()].tolist()
print(f"\nDuplicate column names: {duplicate_column_names}")

print("\nVerification report saved to:")
print((output_dir / "variable_presence_verification.csv").resolve())

============================================================
BRFSS VARIABLE PRESENCE VERIFICATION
============================================================
Dataset shape: (457670, 102)
Expected variables: 102
Unique expected variable names: 102
Expected variables found: 0
Expected variables missing: 102
Actual columns not in expected list: 102

Missing variables:
- _STATE
- SEQNO
- _PSU
- SEXVAR
- GENHLTH
- PHYSHLTH
- MENTHLTH
- POORHLTH
- PRIMINS2
- PERSDOC3
- MEDCOST1
- CHECKUP1
- EXERANY2
- LASTDEN4
- RMVTETH4
- CVDINFR4
- CVDCRHD4
- CVDSTRK3
- ASTHMA3
- ASTHNOW
- CHCSCNC1
- CHCOCNC1
- CHCCOPD3
- ADDEPEV3
- CHCKDNY2
- HAVARTH4
- DIABETE4
- MARITAL
- EDUCA
- RENTHOM1
- VETERAN3
- EMPLOY1
- INCOME3
- DECIDE
- DIFFWALK
- DIFFDRES
- DIFFALON
- SMOKE100
- SMOKDAY2
- USENOW3
- ECIGNOW3
- LCSFIRST
- LCSNUMCG
- LSATISFY
- EMTSUPRT
- SDLONELY
- SDHBILLS
- SDHUTILS
- SDHTRNSP
- HOWSAFE1
- _STSTR
- _LLCPWT
- _PHYS14D
- _MENT14D
- _RACE
- _AGE80
- HTM4
- WTKG3
- _BMI5
- _BMI5CAT
- _RFBMI5
- _CHLDCNT
- _PACKDAY
- _PACKYRS
- _LCSYQTS
- _LCSSMKG
- DRNKANY6
- DROCDY4_
- _RFBING6
- _DRNKWK3
- _RFDRHV9
- _FLSHOT7
- _PNEUMO3
- DIABAGE4
- DIABTYPE
- PREDIAB2
- DIABEDU1
- LCSSCNCR
- LCSLAST_
- LCSNUMC_
- _LCSAGE
- _LCSYSMK
- _LCSCTSN
- _LCSPSTF
- ALCDAY4
- AVEDRNK4
- FLUSHOT7
- FLSHTMY3
- IMFVPLA5
- PNEUVAC4
- _HLTHPL2
- _HCVU654
- _TOTINDA
- _LTASTH1
- _CASTHM1
- _ASTHMS1
- _EDUCAG
- _INCOMG1
- _SMOKER3
- _RFSMOK3
- _CURECI3
- WEIGHT2

Columns outside the expected list:
- State FIPS Code (_STATE)
- Annual Sequence Number (SEQNO)
- Primary Sampling Unit (_PSU)
- Sex of Respondent (SEXVAR)
- General Health (GENHLTH)
- Number of Days Physical Health Not Good (PHYSHLTH)
- Number of Days Mental Health Not Good (MENTHLTH)
- Poor Physical or Mental Health (POORHLTH)
- What is Your Current Primary Source of Health Care Coverage? (PRIMINS2)
- Have Personal Health Care Provider? (PERSDOC3)
- Could Not Afford To See Doctor (MEDCOST1)
- Length of time since last routine checkup (CHECKUP1)
- Exercise in Past 30 Days (EXERANY2)
- Last Visited Dentist or Dental Clinic (LASTDEN4)
- Number of Permanent Teeth Removed (RMVTETH4)
- Ever Diagnosed with Heart Attack (CVDINFR4)
- Ever Diagnosed with Angina or Coronary Heart Disease (CVDCRHD4)
- Ever Diagnosed with a Stroke (CVDSTRK3)
- Ever Told Had Asthma (ASTHMA3)
- Still Have Asthma (ASTHNOW)
- (Ever told) (you had) skin cancer that is not melanoma? (CHCSCNC1)
- (Ever told) (you had)  melanoma or any other types of cancer? (CHCOCNC1)
- Ever told you had C.O.P.D. emphysema or chronic bronchitis? (CHCCOPD3)
- (Ever told) you had a depressive disorder (ADDEPEV3)
- Ever told you have kidney disease? (CHCKDNY2)
- Told Had Arthritis (HAVARTH4)
- (Ever told) you had diabetes (DIABETE4)
- Marital Status (MARITAL)
- Education Level (EDUCA)
- Own or Rent Home (RENTHOM1)
- Are You A Veteran (VETERAN3)
- Employment Status (EMPLOY1)
- Income Level (INCOME3)
- Difficulty Concentrating or Remembering (DECIDE)
- Difficulty Walking or Climbing Stairs (DIFFWALK)
- Difficulty Dressing or Bathing (DIFFDRES)
- Difficulty Doing Errands Alone (DIFFALON)
- Smoked at Least 100 Cigarettes (SMOKE100)
- Frequency of Days Now Smoking (SMOKDAY2)
- Use of Smokeless Tobacco Products (USENOW3)
- Do you now use e-cigarettes, or vaping products every day, some days, or not at all? (ECIGNOW3)
- How old when you first started smoking? (LCSFIRST)
- On average, how many cigarettes do you smoke each day? (LCSNUMCG)
- Satisfaction with life (LSATISFY)
- How often get emotional support needed (EMTSUPRT)
- How often do you feel lonely? (SDLONELY)
- Were you not able to pay your bills? (SDHBILLS)
- Were you not able to pay utility bills or threatened to lose service? (SDHUTILS)
- Has a lack of reliable transportation kept you from appointments, meetings, work, or getting things needed (SDHTRNSP)
- Neighborhood Safe From Crime (HOWSAFE1)
- Sample Design Stratification Variable (_STSTR)
- Final weight: Land-line and cell-phone data (_LLCPWT)
- Computed Physical Health Status (_PHYS14D)
- Computed Mental Health Status (_MENT14D)
- Computed Race-Ethnicity grouping (_RACE)
- Imputed Age value collapsed above 80 (_AGE80)
- Computed Height in Meters (HTM4)
- Computed Weight in Kilograms (WTKG3)
- Computed body mass index (_BMI5)
- Computed body mass index categories (_BMI5CAT)
- Overweight or obese calculated variable (_RFBMI5)
- Computed number of children in household (_CHLDCNT)
- Number of packs of cigarettes smoked per day (_PACKDAY)
- Years smoked reported packs per day (_PACKYRS)
- Number of years since quit smoking cigarettes (_LCSYQTS)
- LCS Smoking Group (_LCSSMKG)
- Drink any alcoholic beverages in past 30 days (DRNKANY6)
- Computed drink-occasions-per-day (DROCDY4_)
- Binge Drinking Calculated Variable (_RFBING6)
- Computed number of drinks of alcohol beverages per week (_DRNKWK3)
- Heavy Alcohol Consumption  Calculated Variable (_RFDRHV9)
- Flu Shot Calculated Variable (_FLSHOT7)
- Pneumonia Vaccination Calculated Variable (_PNEUMO3)
- Age When First Told You Had Diabetes (DIABAGE4)
- What type of diabetes do you have? (DIABTYPE)
- Ever been told by a doctor or other health professional that you have pre-diabetes or borderline diabetes? (PREDIAB2)
- When was the last time you took a course or class in how to manage your diabetes? (DIABEDU1)
- Were any CT or CAT scans done to check for lung cancer? (LCSSCNCR)
- How old when you last smoked? (LCSLAST_)
- On average, how many cigarettes do you smoke each day? (LCSNUMC_)
- Lung Cancer Screening Age Groups (_LCSAGE)
- Number of years smoked cigarettes (_LCSYSMK)
- Had Chest CT Scan for Lung Cancer (_LCSCTSN)
- Meet USPSTF Lung Cancer Screening Guidelines (_LCSPSTF)
- Days in past 30 had alcoholic beverage (ALCDAY4)
- Avg alcoholic drinks per day in past 30 (AVEDRNK4)
- Adult flu shot/spray past 12 mos (FLUSHOT7)
- When did you receive your most recent seasonal flu shot/spray? (FLSHTMY3)
- Where did you get your last flu shot/vaccine? (IMFVPLA5)
- Pneumonia shot ever (PNEUVAC4)
- Have any health insurance (_HLTHPL2)
- Respondents aged 18-64 with health insurance (_HCVU654)
- Leisure Time Physical Activity Calculated Variable (_TOTINDA)
- Lifetime Asthma Calculated Variable (_LTASTH1)
- Current Asthma Calculated Variable (_CASTHM1)
- Computed Asthma Status (_ASTHMS1)
- Computed level of education completed categories (_EDUCAG)
- Computed income categories (_INCOMG1)
- Computed Smoking Status (_SMOKER3)
- Current Smoking Calculated Variable (_RFSMOK3)
- Current E-cigarette User Calculated Variable (_CURECI3)
- Reported Weight in Pounds (WEIGHT2)

Duplicate column names: []

Verification report saved to:
C:\Users\USER\OneDrive\Desktop\BRFSS\BRFSS_Validation_Reports\variable_presence_verification.csv

In [46]:

print("First 30 actual column names:")
for i, col in enumerate(data.columns[:30], start=1):
    print(f"{i}. {repr(col)}")

print("\nColumn names as a list:")
print(data.columns.tolist())

First 30 actual column names:
1. 'State FIPS Code (_STATE)'
2. 'Annual Sequence Number (SEQNO)'
3. 'Primary Sampling Unit (_PSU)'
4. 'Sex of Respondent (SEXVAR)'
5. 'General Health (GENHLTH)'
6. 'Number of Days Physical Health Not Good (PHYSHLTH)'
7. 'Number of Days Mental Health Not Good (MENTHLTH)'
8. 'Poor Physical or Mental Health (POORHLTH)'
9. 'What is Your Current Primary Source of Health Care Coverage? (PRIMINS2)'
10. 'Have Personal Health Care Provider? (PERSDOC3)'
11. 'Could Not Afford To See Doctor (MEDCOST1)'
12. 'Length of time since last routine checkup (CHECKUP1)'
13. 'Exercise in Past 30 Days (EXERANY2)'
14. 'Last Visited Dentist or Dental Clinic (LASTDEN4)'
15. 'Number of Permanent Teeth Removed (RMVTETH4)'
16. 'Ever Diagnosed with Heart Attack (CVDINFR4)'
17. 'Ever Diagnosed with Angina or Coronary Heart Disease (CVDCRHD4)'
18. 'Ever Diagnosed with a Stroke (CVDSTRK3)'
19. 'Ever Told Had Asthma (ASTHMA3)'
20. 'Still Have Asthma (ASTHNOW)'
21. '(Ever told) (you had) skin cancer that is not melanoma? (CHCSCNC1)'
22. '(Ever told) (you had)  melanoma or any other types of cancer? (CHCOCNC1)'
23. 'Ever told you had C.O.P.D. emphysema or chronic bronchitis? (CHCCOPD3)'
24. '(Ever told) you had a depressive disorder (ADDEPEV3)'
25. 'Ever told you have kidney disease? (CHCKDNY2)'
26. 'Told Had Arthritis (HAVARTH4)'
27. '(Ever told) you had diabetes (DIABETE4)'
28. 'Marital Status (MARITAL)'
29. 'Education Level (EDUCA)'
30. 'Own or Rent Home (RENTHOM1)'

Column names as a list:
['State FIPS Code (_STATE)', 'Annual Sequence Number (SEQNO)', 'Primary Sampling Unit (_PSU)', 'Sex of Respondent (SEXVAR)', 'General Health (GENHLTH)', 'Number of Days Physical Health Not Good (PHYSHLTH)', 'Number of Days Mental Health Not Good (MENTHLTH)', 'Poor Physical or Mental Health (POORHLTH)', 'What is Your Current Primary Source of Health Care Coverage? (PRIMINS2)', 'Have Personal Health Care Provider? (PERSDOC3)', 'Could Not Afford To See Doctor (MEDCOST1)', 'Length of time since last routine checkup (CHECKUP1)', 'Exercise in Past 30 Days (EXERANY2)', 'Last Visited Dentist or Dental Clinic (LASTDEN4)', 'Number of Permanent Teeth Removed (RMVTETH4)', 'Ever Diagnosed with Heart Attack (CVDINFR4)', 'Ever Diagnosed with Angina or Coronary Heart Disease (CVDCRHD4)', 'Ever Diagnosed with a Stroke (CVDSTRK3)', 'Ever Told Had Asthma (ASTHMA3)', 'Still Have Asthma (ASTHNOW)', '(Ever told) (you had) skin cancer that is not melanoma? (CHCSCNC1)', '(Ever told) (you had)  melanoma or any other types of cancer? (CHCOCNC1)', 'Ever told you had C.O.P.D. emphysema or chronic bronchitis? (CHCCOPD3)', '(Ever told) you had a depressive disorder (ADDEPEV3)', 'Ever told you have kidney disease? (CHCKDNY2)', 'Told Had Arthritis (HAVARTH4)', '(Ever told) you had diabetes (DIABETE4)', 'Marital Status (MARITAL)', 'Education Level (EDUCA)', 'Own or Rent Home (RENTHOM1)', 'Are You A Veteran (VETERAN3)', 'Employment Status (EMPLOY1)', 'Income Level (INCOME3)', 'Difficulty Concentrating or Remembering (DECIDE)', 'Difficulty Walking or Climbing Stairs (DIFFWALK)', 'Difficulty Dressing or Bathing (DIFFDRES)', 'Difficulty Doing Errands Alone (DIFFALON)', 'Smoked at Least 100 Cigarettes (SMOKE100)', 'Frequency of Days Now Smoking (SMOKDAY2)', 'Use of Smokeless Tobacco Products (USENOW3)', 'Do you now use e-cigarettes, or vaping products every day, some days, or not at all? (ECIGNOW3)', 'How old when you first started smoking? (LCSFIRST)', 'On average, how many cigarettes do you smoke each day? (LCSNUMCG)', 'Satisfaction with life (LSATISFY)', 'How often get emotional support needed (EMTSUPRT)', 'How often do you feel lonely? (SDLONELY)', 'Were you not able to pay your bills? (SDHBILLS)', 'Were you not able to pay utility bills or threatened to lose service? (SDHUTILS)', 'Has a lack of reliable transportation kept you from appointments, meetings, work, or getting things needed (SDHTRNSP)', 'Neighborhood Safe From Crime (HOWSAFE1)', 'Sample Design Stratification Variable (_STSTR)', 'Final weight: Land-line and cell-phone data (_LLCPWT)', 'Computed Physical Health Status (_PHYS14D)', 'Computed Mental Health Status (_MENT14D)', 'Computed Race-Ethnicity grouping (_RACE)', 'Imputed Age value collapsed above 80 (_AGE80)', 'Computed Height in Meters (HTM4)', 'Computed Weight in Kilograms (WTKG3)', 'Computed body mass index (_BMI5)', 'Computed body mass index categories (_BMI5CAT)', 'Overweight or obese calculated variable (_RFBMI5)', 'Computed number of children in household (_CHLDCNT)', 'Number of packs of cigarettes smoked per day (_PACKDAY)', 'Years smoked reported packs per day (_PACKYRS)', 'Number of years since quit smoking cigarettes (_LCSYQTS)', 'LCS Smoking Group (_LCSSMKG)', 'Drink any alcoholic beverages in past 30 days (DRNKANY6)', 'Computed drink-occasions-per-day (DROCDY4_)', 'Binge Drinking Calculated Variable (_RFBING6)', 'Computed number of drinks of alcohol beverages per week (_DRNKWK3)', 'Heavy Alcohol Consumption  Calculated Variable (_RFDRHV9)', 'Flu Shot Calculated Variable (_FLSHOT7)', 'Pneumonia Vaccination Calculated Variable (_PNEUMO3)', 'Age When First Told You Had Diabetes (DIABAGE4)', 'What type of diabetes do you have? (DIABTYPE)', 'Ever been told by a doctor or other health professional that you have pre-diabetes or borderline diabetes? (PREDIAB2)', 'When was the last time you took a course or class in how to manage your diabetes? (DIABEDU1)', 'Were any CT or CAT scans done to check for lung cancer? (LCSSCNCR)', 'How old when you last smoked? (LCSLAST_)', 'On average, how many cigarettes do you smoke each day? (LCSNUMC_)', 'Lung Cancer Screening Age Groups (_LCSAGE)', 'Number of years smoked cigarettes (_LCSYSMK)', 'Had Chest CT Scan for Lung Cancer (_LCSCTSN)', 'Meet USPSTF Lung Cancer Screening Guidelines (_LCSPSTF)', 'Days in past 30 had alcoholic beverage (ALCDAY4)', 'Avg alcoholic drinks per day in past 30 (AVEDRNK4)', 'Adult flu shot/spray past 12 mos (FLUSHOT7)', 'When did you receive your most recent seasonal flu shot/spray? (FLSHTMY3)', 'Where did you get your last flu shot/vaccine? (IMFVPLA5)', 'Pneumonia shot ever (PNEUVAC4)', 'Have any health insurance (_HLTHPL2)', 'Respondents aged 18-64 with health insurance (_HCVU654)', 'Leisure Time Physical Activity Calculated Variable (_TOTINDA)', 'Lifetime Asthma Calculated Variable (_LTASTH1)', 'Current Asthma Calculated Variable (_CASTHM1)', 'Computed Asthma Status (_ASTHMS1)', 'Computed level of education completed categories (_EDUCAG)', 'Computed income categories (_INCOMG1)', 'Computed Smoking Status (_SMOKER3)', 'Current Smoking Calculated Variable (_RFSMOK3)', 'Current E-cigarette User Calculated Variable (_CURECI3)', 'Reported Weight in Pounds (WEIGHT2)']

In [47]:

import re
import pandas as pd
from pathlib import Path

# Extract the BRFSS code from the end of each descriptive column name
def extract_brfss_code(column_name):
    match = re.search(r"\(([A-Z0-9_]+)\)\s*$", str(column_name).strip())
    return match.group(1) if match else None

actual_codes = [extract_brfss_code(col) for col in data.columns]

# Check whether all columns have a recognizable BRFSS code
columns_without_codes = [
    col for col, code in zip(data.columns, actual_codes)
    if code is None
]

# Check duplicate codes
valid_codes = [code for code in actual_codes if code is not None]
duplicate_codes = pd.Series(valid_codes)
duplicate_codes = duplicate_codes[duplicate_codes.duplicated()].unique().tolist()

# Expected codes from the previously documented variable list
expected_codes = set(expected_variables)
actual_code_set = set(valid_codes)

missing_codes = sorted(expected_codes - actual_code_set)
unexpected_codes = sorted(actual_code_set - expected_codes)

# Create a report for every actual column
verification_report = pd.DataFrame({
    "Original_Column_Name": list(data.columns),
    "Extracted_BRFSS_Code": actual_codes,
    "Code_Recognized": [code is not None for code in actual_codes],
    "Code_In_Expected_List": [
        code in expected_codes if code is not None else False
        for code in actual_codes
    ],
    "Data_Type": [str(data[col].dtype) for col in data.columns],
    "Missing_Values": [int(data[col].isna().sum()) for col in data.columns],
    "Unique_Values": [int(data[col].nunique(dropna=True)) for col in data.columns]
})

# Save the report
output_dir = Path.cwd() / "BRFSS_Validation_Reports"
output_dir.mkdir(parents=True, exist_ok=True)

verification_report.to_csv(
    output_dir / "variable_code_verification.csv",
    index=False,
    encoding="utf-8-sig"
)

# Print results
print("=" * 60)
print("BRFSS VARIABLE CODE VERIFICATION")
print("=" * 60)
print(f"Dataset shape: {data.shape}")
print(f"Total columns: {len(data.columns)}")
print(f"Recognized BRFSS codes: {sum(code is not None for code in actual_codes)}")
print(f"Columns without recognized codes: {len(columns_without_codes)}")
print(f"Unique extracted codes: {len(actual_code_set)}")
print(f"Duplicate extracted codes: {duplicate_codes}")
print(f"Expected codes missing: {len(missing_codes)}")
print(f"Unexpected codes: {len(unexpected_codes)}")

if missing_codes:
    print("\nMissing expected codes:")
    print(missing_codes)

if unexpected_codes:
    print("\nUnexpected extracted codes:")
    print(unexpected_codes)

if columns_without_codes:
    print("\nColumns without recognizable codes:")
    print(columns_without_codes)

print("\nFirst 10 mappings:")
print(verification_report[
    ["Original_Column_Name", "Extracted_BRFSS_Code"]
].head(10).to_string(index=False))

print("\nReport saved to:")
print((output_dir / "variable_code_verification.csv").resolve())

============================================================
BRFSS VARIABLE CODE VERIFICATION
============================================================
Dataset shape: (457670, 102)
Total columns: 102
Recognized BRFSS codes: 102
Columns without recognized codes: 0
Unique extracted codes: 102
Duplicate extracted codes: []
Expected codes missing: 0
Unexpected codes: 0

First 10 mappings:
                                                   Original_Column_Name Extracted_BRFSS_Code
                                               State FIPS Code (_STATE)               _STATE
                                         Annual Sequence Number (SEQNO)                SEQNO
                                           Primary Sampling Unit (_PSU)                 _PSU
                                             Sex of Respondent (SEXVAR)               SEXVAR
                                               General Health (GENHLTH)              GENHLTH
                     Number of Days Physical Health Not Good (PHYSHLTH)             PHYSHLTH
                       Number of Days Mental Health Not Good (MENTHLTH)             MENTHLTH
                              Poor Physical or Mental Health (POORHLTH)             POORHLTH
What is Your Current Primary Source of Health Care Coverage? (PRIMINS2)             PRIMINS2
                         Have Personal Health Care Provider? (PERSDOC3)             PERSDOC3

Report saved to:
C:\Users\USER\OneDrive\Desktop\BRFSS\BRFSS_Validation_Reports\variable_code_verification.csv